// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/get(FunctionInvocations_invokeGet)`.
    func FunctionInvocations_invokeGet(_ input: Operations.FunctionInvocations_invokeGet.Input) async throws -> Operations.FunctionInvocations_invokeGet.Output
    /// - Remark: HTTP `POST /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/post(FunctionInvocations_invokePost)`.
    func FunctionInvocations_invokePost(_ input: Operations.FunctionInvocations_invokePost.Input) async throws -> Operations.FunctionInvocations_invokePost.Output
    /// - Remark: HTTP `PATCH /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/patch(FunctionInvocations_invokePatch)`.
    func FunctionInvocations_invokePatch(_ input: Operations.FunctionInvocations_invokePatch.Input) async throws -> Operations.FunctionInvocations_invokePatch.Output
    /// - Remark: HTTP `PUT /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/put(FunctionInvocations_invokePut)`.
    func FunctionInvocations_invokePut(_ input: Operations.FunctionInvocations_invokePut.Input) async throws -> Operations.FunctionInvocations_invokePut.Output
    /// - Remark: HTTP `DELETE /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/delete(FunctionInvocations_invokeDelete)`.
    func FunctionInvocations_invokeDelete(_ input: Operations.FunctionInvocations_invokeDelete.Input) async throws -> Operations.FunctionInvocations_invokeDelete.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/get(FunctionInvocations_invokeGet)`.
    internal func FunctionInvocations_invokeGet(
        path: Operations.FunctionInvocations_invokeGet.Input.Path,
        headers: Operations.FunctionInvocations_invokeGet.Input.Headers = .init()
    ) async throws -> Operations.FunctionInvocations_invokeGet.Output {
        try await FunctionInvocations_invokeGet(Operations.FunctionInvocations_invokeGet.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/post(FunctionInvocations_invokePost)`.
    internal func FunctionInvocations_invokePost(
        path: Operations.FunctionInvocations_invokePost.Input.Path,
        headers: Operations.FunctionInvocations_invokePost.Input.Headers = .init(),
        body: Operations.FunctionInvocations_invokePost.Input.Body? = nil
    ) async throws -> Operations.FunctionInvocations_invokePost.Output {
        try await FunctionInvocations_invokePost(Operations.FunctionInvocations_invokePost.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PATCH /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/patch(FunctionInvocations_invokePatch)`.
    internal func FunctionInvocations_invokePatch(
        path: Operations.FunctionInvocations_invokePatch.Input.Path,
        headers: Operations.FunctionInvocations_invokePatch.Input.Headers = .init(),
        body: Operations.FunctionInvocations_invokePatch.Input.Body? = nil
    ) async throws -> Operations.FunctionInvocations_invokePatch.Output {
        try await FunctionInvocations_invokePatch(Operations.FunctionInvocations_invokePatch.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PUT /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/put(FunctionInvocations_invokePut)`.
    internal func FunctionInvocations_invokePut(
        path: Operations.FunctionInvocations_invokePut.Input.Path,
        headers: Operations.FunctionInvocations_invokePut.Input.Headers = .init(),
        body: Operations.FunctionInvocations_invokePut.Input.Body? = nil
    ) async throws -> Operations.FunctionInvocations_invokePut.Output {
        try await FunctionInvocations_invokePut(Operations.FunctionInvocations_invokePut.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/delete(FunctionInvocations_invokeDelete)`.
    internal func FunctionInvocations_invokeDelete(
        path: Operations.FunctionInvocations_invokeDelete.Input.Path,
        headers: Operations.FunctionInvocations_invokeDelete.Input.Headers = .init(),
        body: Operations.FunctionInvocations_invokeDelete.Input.Body? = nil
    ) async throws -> Operations.FunctionInvocations_invokeDelete.Output {
        try await FunctionInvocations_invokeDelete(Operations.FunctionInvocations_invokeDelete.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {
    /// Supabase Edge Functions endpoint
    internal enum Server1 {
        /// Supabase Edge Functions endpoint
        ///
        /// - Parameters:
        ///   - baseUrl:
        internal static func url(baseUrl: Swift.String = "") throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "{baseUrl}",
                variables: [
                    .init(
                        name: "baseUrl",
                        value: baseUrl
                    )
                ]
            )
        }
    }
    /// Supabase Edge Functions endpoint
    ///
    /// - Parameters:
    ///   - baseUrl:
    @available(*, deprecated, renamed: "Servers.Server1.url")
    internal static func server1(baseUrl: Swift.String = "") throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "{baseUrl}",
            variables: [
                .init(
                    name: "baseUrl",
                    value: baseUrl
                )
            ]
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
internal enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/FunctionsError`.
        internal struct FunctionsError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/FunctionsError/message`.
            internal var message: Swift.String?
            /// Creates a new `FunctionsError`.
            ///
            /// - Parameters:
            ///   - message:
            internal init(message: Swift.String? = nil) {
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case message
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    internal enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    internal enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    internal enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    internal enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
internal enum Operations {
    /// - Remark: HTTP `GET /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/get(FunctionInvocations_invokeGet)`.
    internal enum FunctionInvocations_invokeGet {
        internal static let id: Swift.String = "FunctionInvocations_invokeGet"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/path/functionName`.
                internal var functionName: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - functionName:
                internal init(functionName: Swift.String) {
                    self.functionName = functionName
                }
            }
            internal var path: Operations.FunctionInvocations_invokeGet.Input.Path
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/header/x-region`.
                internal var x_hyphen_region: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokeGet.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - x_hyphen_region:
                ///   - accept:
                internal init(
                    x_hyphen_region: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokeGet.AcceptableContentType>] = .defaultValues()
                ) {
                    self.x_hyphen_region = x_hyphen_region
                    self.accept = accept
                }
            }
            internal var headers: Operations.FunctionInvocations_invokeGet.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            internal init(
                path: Operations.FunctionInvocations_invokeGet.Input.Path,
                headers: Operations.FunctionInvocations_invokeGet.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    internal var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokeGet.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokeGet.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/get(FunctionInvocations_invokeGet)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.FunctionInvocations_invokeGet.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.FunctionInvocations_invokeGet.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/GET/responses/default/content/application\/json`.
                    case json(Components.Schemas.FunctionsError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.FunctionsError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokeGet.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokeGet.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/get(FunctionInvocations_invokeGet)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.FunctionInvocations_invokeGet.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.FunctionInvocations_invokeGet.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case binary
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/octet-stream":
                    self = .binary
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .binary:
                    return "application/octet-stream"
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .binary,
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/post(FunctionInvocations_invokePost)`.
    internal enum FunctionInvocations_invokePost {
        internal static let id: Swift.String = "FunctionInvocations_invokePost"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/path/functionName`.
                internal var functionName: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - functionName:
                internal init(functionName: Swift.String) {
                    self.functionName = functionName
                }
            }
            internal var path: Operations.FunctionInvocations_invokePost.Input.Path
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/header/x-region`.
                internal var x_hyphen_region: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokePost.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - x_hyphen_region:
                ///   - accept:
                internal init(
                    x_hyphen_region: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokePost.AcceptableContentType>] = .defaultValues()
                ) {
                    self.x_hyphen_region = x_hyphen_region
                    self.accept = accept
                }
            }
            internal var headers: Operations.FunctionInvocations_invokePost.Input.Headers
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/requestBody/content/application\/octet-stream`.
                case binary(OpenAPIRuntime.HTTPBody)
            }
            internal var body: Operations.FunctionInvocations_invokePost.Input.Body?
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.FunctionInvocations_invokePost.Input.Path,
                headers: Operations.FunctionInvocations_invokePost.Input.Headers = .init(),
                body: Operations.FunctionInvocations_invokePost.Input.Body? = nil
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    internal var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokePost.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokePost.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/post(FunctionInvocations_invokePost)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.FunctionInvocations_invokePost.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.FunctionInvocations_invokePost.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/POST/responses/default/content/application\/json`.
                    case json(Components.Schemas.FunctionsError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.FunctionsError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokePost.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokePost.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/post(FunctionInvocations_invokePost)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.FunctionInvocations_invokePost.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.FunctionInvocations_invokePost.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case binary
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/octet-stream":
                    self = .binary
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .binary:
                    return "application/octet-stream"
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .binary,
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `PATCH /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/patch(FunctionInvocations_invokePatch)`.
    internal enum FunctionInvocations_invokePatch {
        internal static let id: Swift.String = "FunctionInvocations_invokePatch"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/path/functionName`.
                internal var functionName: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - functionName:
                internal init(functionName: Swift.String) {
                    self.functionName = functionName
                }
            }
            internal var path: Operations.FunctionInvocations_invokePatch.Input.Path
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/header/x-region`.
                internal var x_hyphen_region: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokePatch.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - x_hyphen_region:
                ///   - accept:
                internal init(
                    x_hyphen_region: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokePatch.AcceptableContentType>] = .defaultValues()
                ) {
                    self.x_hyphen_region = x_hyphen_region
                    self.accept = accept
                }
            }
            internal var headers: Operations.FunctionInvocations_invokePatch.Input.Headers
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/requestBody/content/application\/octet-stream`.
                case binary(OpenAPIRuntime.HTTPBody)
            }
            internal var body: Operations.FunctionInvocations_invokePatch.Input.Body?
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.FunctionInvocations_invokePatch.Input.Path,
                headers: Operations.FunctionInvocations_invokePatch.Input.Headers = .init(),
                body: Operations.FunctionInvocations_invokePatch.Input.Body? = nil
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    internal var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokePatch.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokePatch.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/patch(FunctionInvocations_invokePatch)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.FunctionInvocations_invokePatch.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.FunctionInvocations_invokePatch.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PATCH/responses/default/content/application\/json`.
                    case json(Components.Schemas.FunctionsError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.FunctionsError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokePatch.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokePatch.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/patch(FunctionInvocations_invokePatch)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.FunctionInvocations_invokePatch.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.FunctionInvocations_invokePatch.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case binary
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/octet-stream":
                    self = .binary
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .binary:
                    return "application/octet-stream"
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .binary,
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `PUT /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/put(FunctionInvocations_invokePut)`.
    internal enum FunctionInvocations_invokePut {
        internal static let id: Swift.String = "FunctionInvocations_invokePut"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/path/functionName`.
                internal var functionName: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - functionName:
                internal init(functionName: Swift.String) {
                    self.functionName = functionName
                }
            }
            internal var path: Operations.FunctionInvocations_invokePut.Input.Path
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/header/x-region`.
                internal var x_hyphen_region: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokePut.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - x_hyphen_region:
                ///   - accept:
                internal init(
                    x_hyphen_region: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokePut.AcceptableContentType>] = .defaultValues()
                ) {
                    self.x_hyphen_region = x_hyphen_region
                    self.accept = accept
                }
            }
            internal var headers: Operations.FunctionInvocations_invokePut.Input.Headers
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/requestBody/content/application\/octet-stream`.
                case binary(OpenAPIRuntime.HTTPBody)
            }
            internal var body: Operations.FunctionInvocations_invokePut.Input.Body?
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.FunctionInvocations_invokePut.Input.Path,
                headers: Operations.FunctionInvocations_invokePut.Input.Headers = .init(),
                body: Operations.FunctionInvocations_invokePut.Input.Body? = nil
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    internal var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokePut.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokePut.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/put(FunctionInvocations_invokePut)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.FunctionInvocations_invokePut.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.FunctionInvocations_invokePut.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/PUT/responses/default/content/application\/json`.
                    case json(Components.Schemas.FunctionsError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.FunctionsError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokePut.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokePut.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/put(FunctionInvocations_invokePut)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.FunctionInvocations_invokePut.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.FunctionInvocations_invokePut.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case binary
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/octet-stream":
                    self = .binary
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .binary:
                    return "application/octet-stream"
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .binary,
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `DELETE /functions/v1/{functionName}`.
    /// - Remark: Generated from `#/paths//functions/v1/{functionName}/delete(FunctionInvocations_invokeDelete)`.
    internal enum FunctionInvocations_invokeDelete {
        internal static let id: Swift.String = "FunctionInvocations_invokeDelete"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/path/functionName`.
                internal var functionName: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - functionName:
                internal init(functionName: Swift.String) {
                    self.functionName = functionName
                }
            }
            internal var path: Operations.FunctionInvocations_invokeDelete.Input.Path
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/header/x-region`.
                internal var x_hyphen_region: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokeDelete.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - x_hyphen_region:
                ///   - accept:
                internal init(
                    x_hyphen_region: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.FunctionInvocations_invokeDelete.AcceptableContentType>] = .defaultValues()
                ) {
                    self.x_hyphen_region = x_hyphen_region
                    self.accept = accept
                }
            }
            internal var headers: Operations.FunctionInvocations_invokeDelete.Input.Headers
            /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/requestBody/content/application\/octet-stream`.
                case binary(OpenAPIRuntime.HTTPBody)
            }
            internal var body: Operations.FunctionInvocations_invokeDelete.Input.Body?
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.FunctionInvocations_invokeDelete.Input.Path,
                headers: Operations.FunctionInvocations_invokeDelete.Input.Headers = .init(),
                body: Operations.FunctionInvocations_invokeDelete.Input.Body? = nil
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    internal var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokeDelete.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokeDelete.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/delete(FunctionInvocations_invokeDelete)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.FunctionInvocations_invokeDelete.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.FunctionInvocations_invokeDelete.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/functions/v1/{functionName}/DELETE/responses/default/content/application\/json`.
                    case json(Components.Schemas.FunctionsError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.FunctionsError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.FunctionInvocations_invokeDelete.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.FunctionInvocations_invokeDelete.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//functions/v1/{functionName}/delete(FunctionInvocations_invokeDelete)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.FunctionInvocations_invokeDelete.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.FunctionInvocations_invokeDelete.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case binary
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/octet-stream":
                    self = .binary
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .binary:
                    return "application/octet-stream"
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .binary,
                    .json
                ]
            }
        }
    }
}
