// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
import HTTPTypes
internal struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    internal init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// - Remark: HTTP `POST /rpc/{functionName}`.
    /// - Remark: Generated from `#/paths//rpc/{functionName}/post(RpcOperations_rpc)`.
    internal func RpcOperations_rpc(_ input: Operations.RpcOperations_rpc.Input) async throws -> Operations.RpcOperations_rpc.Output {
        try await client.send(
            input: input,
            forOperation: Operations.RpcOperations_rpc.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/rpc/{}",
                    parameters: [
                        input.path.functionName
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "params",
                    value: input.query.params
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Prefer",
                    value: input.headers.Prefer
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Content-Profile",
                    value: input.headers.Content_hyphen_Profile
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Accept-Profile",
                    value: input.headers.Accept_hyphen_Profile
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RpcOperations_rpc.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            OpenAPIRuntime.OpenAPIValueContainer.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RpcOperations_rpc.Output.Default.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PostgRESTError.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .`default`(
                        statusCode: response.status.code,
                        .init(body: body)
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /{table}`.
    /// - Remark: Generated from `#/paths//{table}/get(TableOperations_from)`.
    internal func TableOperations_from(_ input: Operations.TableOperations_from.Input) async throws -> Operations.TableOperations_from.Output {
        try await client.send(
            input: input,
            forOperation: Operations.TableOperations_from.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/{}",
                    parameters: [
                        input.path.table
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "params",
                    value: input.query.params
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Range",
                    value: input.headers.Range
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Prefer",
                    value: input.headers.Prefer
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Accept-Profile",
                    value: input.headers.Accept_hyphen_Profile
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.TableOperations_from.Output.Ok.Headers = .init(
                        Content_hyphen_Range: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Content-Range",
                            as: Swift.String.self
                        ),
                        Preference_hyphen_Applied: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Preference-Applied",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_from.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            OpenAPIRuntime.OpenAPIValueContainer.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_from.Output.Default.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PostgRESTError.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .`default`(
                        statusCode: response.status.code,
                        .init(body: body)
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /{table}`.
    /// - Remark: Generated from `#/paths//{table}/post(TableOperations_insert)`.
    internal func TableOperations_insert(_ input: Operations.TableOperations_insert.Input) async throws -> Operations.TableOperations_insert.Output {
        try await client.send(
            input: input,
            forOperation: Operations.TableOperations_insert.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/{}",
                    parameters: [
                        input.path.table
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "params",
                    value: input.query.params
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Prefer",
                    value: input.headers.Prefer
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Content-Profile",
                    value: input.headers.Content_hyphen_Profile
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Accept-Profile",
                    value: input.headers.Accept_hyphen_Profile
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let headers: Operations.TableOperations_insert.Output.Created.Headers = .init(
                        Content_hyphen_Range: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Content-Range",
                            as: Swift.String.self
                        ),
                        Preference_hyphen_Applied: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Preference-Applied",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_insert.Output.Created.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            OpenAPIRuntime.OpenAPIValueContainer.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .created(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_insert.Output.Default.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PostgRESTError.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .`default`(
                        statusCode: response.status.code,
                        .init(body: body)
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PATCH /{table}`.
    /// - Remark: Generated from `#/paths//{table}/patch(TableOperations_update)`.
    internal func TableOperations_update(_ input: Operations.TableOperations_update.Input) async throws -> Operations.TableOperations_update.Output {
        try await client.send(
            input: input,
            forOperation: Operations.TableOperations_update.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/{}",
                    parameters: [
                        input.path.table
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "params",
                    value: input.query.params
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Prefer",
                    value: input.headers.Prefer
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Content-Profile",
                    value: input.headers.Content_hyphen_Profile
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Accept-Profile",
                    value: input.headers.Accept_hyphen_Profile
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.TableOperations_update.Output.Ok.Headers = .init(
                        Content_hyphen_Range: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Content-Range",
                            as: Swift.String.self
                        ),
                        Preference_hyphen_Applied: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Preference-Applied",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_update.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            OpenAPIRuntime.OpenAPIValueContainer.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_update.Output.Default.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PostgRESTError.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .`default`(
                        statusCode: response.status.code,
                        .init(body: body)
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PUT /{table}`.
    /// - Remark: Generated from `#/paths//{table}/put(TableOperations_upsert)`.
    internal func TableOperations_upsert(_ input: Operations.TableOperations_upsert.Input) async throws -> Operations.TableOperations_upsert.Output {
        try await client.send(
            input: input,
            forOperation: Operations.TableOperations_upsert.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/{}",
                    parameters: [
                        input.path.table
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "params",
                    value: input.query.params
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Prefer",
                    value: input.headers.Prefer
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Content-Profile",
                    value: input.headers.Content_hyphen_Profile
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Accept-Profile",
                    value: input.headers.Accept_hyphen_Profile
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.TableOperations_upsert.Output.Ok.Headers = .init(
                        Content_hyphen_Range: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Content-Range",
                            as: Swift.String.self
                        ),
                        Preference_hyphen_Applied: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Preference-Applied",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_upsert.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            OpenAPIRuntime.OpenAPIValueContainer.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_upsert.Output.Default.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PostgRESTError.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .`default`(
                        statusCode: response.status.code,
                        .init(body: body)
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /{table}`.
    /// - Remark: Generated from `#/paths//{table}/delete(TableOperations_deleteRows)`.
    internal func TableOperations_deleteRows(_ input: Operations.TableOperations_deleteRows.Input) async throws -> Operations.TableOperations_deleteRows.Output {
        try await client.send(
            input: input,
            forOperation: Operations.TableOperations_deleteRows.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/{}",
                    parameters: [
                        input.path.table
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "params",
                    value: input.query.params
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Prefer",
                    value: input.headers.Prefer
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Content-Profile",
                    value: input.headers.Content_hyphen_Profile
                )
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Accept-Profile",
                    value: input.headers.Accept_hyphen_Profile
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.TableOperations_deleteRows.Output.Ok.Headers = .init(
                        Content_hyphen_Range: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Content-Range",
                            as: Swift.String.self
                        ),
                        Preference_hyphen_Applied: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "Preference-Applied",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_deleteRows.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            OpenAPIRuntime.OpenAPIValueContainer.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.TableOperations_deleteRows.Output.Default.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PostgRESTError.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .`default`(
                        statusCode: response.status.code,
                        .init(body: body)
                    )
                }
            }
        )
    }
}
