// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /rpc/{functionName}`.
    /// - Remark: Generated from `#/paths//rpc/{functionName}/post(RpcOperations_rpc)`.
    func RpcOperations_rpc(_ input: Operations.RpcOperations_rpc.Input) async throws -> Operations.RpcOperations_rpc.Output
    /// - Remark: HTTP `GET /{table}`.
    /// - Remark: Generated from `#/paths//{table}/get(TableOperations_from)`.
    func TableOperations_from(_ input: Operations.TableOperations_from.Input) async throws -> Operations.TableOperations_from.Output
    /// - Remark: HTTP `POST /{table}`.
    /// - Remark: Generated from `#/paths//{table}/post(TableOperations_insert)`.
    func TableOperations_insert(_ input: Operations.TableOperations_insert.Input) async throws -> Operations.TableOperations_insert.Output
    /// - Remark: HTTP `PATCH /{table}`.
    /// - Remark: Generated from `#/paths//{table}/patch(TableOperations_update)`.
    func TableOperations_update(_ input: Operations.TableOperations_update.Input) async throws -> Operations.TableOperations_update.Output
    /// - Remark: HTTP `PUT /{table}`.
    /// - Remark: Generated from `#/paths//{table}/put(TableOperations_upsert)`.
    func TableOperations_upsert(_ input: Operations.TableOperations_upsert.Input) async throws -> Operations.TableOperations_upsert.Output
    /// - Remark: HTTP `DELETE /{table}`.
    /// - Remark: Generated from `#/paths//{table}/delete(TableOperations_deleteRows)`.
    func TableOperations_deleteRows(_ input: Operations.TableOperations_deleteRows.Input) async throws -> Operations.TableOperations_deleteRows.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /rpc/{functionName}`.
    /// - Remark: Generated from `#/paths//rpc/{functionName}/post(RpcOperations_rpc)`.
    internal func RpcOperations_rpc(
        path: Operations.RpcOperations_rpc.Input.Path,
        query: Operations.RpcOperations_rpc.Input.Query = .init(),
        headers: Operations.RpcOperations_rpc.Input.Headers = .init(),
        body: Operations.RpcOperations_rpc.Input.Body
    ) async throws -> Operations.RpcOperations_rpc.Output {
        try await RpcOperations_rpc(Operations.RpcOperations_rpc.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /{table}`.
    /// - Remark: Generated from `#/paths//{table}/get(TableOperations_from)`.
    internal func TableOperations_from(
        path: Operations.TableOperations_from.Input.Path,
        query: Operations.TableOperations_from.Input.Query = .init(),
        headers: Operations.TableOperations_from.Input.Headers = .init()
    ) async throws -> Operations.TableOperations_from.Output {
        try await TableOperations_from(Operations.TableOperations_from.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /{table}`.
    /// - Remark: Generated from `#/paths//{table}/post(TableOperations_insert)`.
    internal func TableOperations_insert(
        path: Operations.TableOperations_insert.Input.Path,
        query: Operations.TableOperations_insert.Input.Query = .init(),
        headers: Operations.TableOperations_insert.Input.Headers = .init(),
        body: Operations.TableOperations_insert.Input.Body
    ) async throws -> Operations.TableOperations_insert.Output {
        try await TableOperations_insert(Operations.TableOperations_insert.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PATCH /{table}`.
    /// - Remark: Generated from `#/paths//{table}/patch(TableOperations_update)`.
    internal func TableOperations_update(
        path: Operations.TableOperations_update.Input.Path,
        query: Operations.TableOperations_update.Input.Query = .init(),
        headers: Operations.TableOperations_update.Input.Headers = .init(),
        body: Operations.TableOperations_update.Input.Body
    ) async throws -> Operations.TableOperations_update.Output {
        try await TableOperations_update(Operations.TableOperations_update.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `PUT /{table}`.
    /// - Remark: Generated from `#/paths//{table}/put(TableOperations_upsert)`.
    internal func TableOperations_upsert(
        path: Operations.TableOperations_upsert.Input.Path,
        query: Operations.TableOperations_upsert.Input.Query = .init(),
        headers: Operations.TableOperations_upsert.Input.Headers = .init(),
        body: Operations.TableOperations_upsert.Input.Body
    ) async throws -> Operations.TableOperations_upsert.Output {
        try await TableOperations_upsert(Operations.TableOperations_upsert.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /{table}`.
    /// - Remark: Generated from `#/paths//{table}/delete(TableOperations_deleteRows)`.
    internal func TableOperations_deleteRows(
        path: Operations.TableOperations_deleteRows.Input.Path,
        query: Operations.TableOperations_deleteRows.Input.Query = .init(),
        headers: Operations.TableOperations_deleteRows.Input.Headers = .init()
    ) async throws -> Operations.TableOperations_deleteRows.Output {
        try await TableOperations_deleteRows(Operations.TableOperations_deleteRows.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {
    /// Supabase PostgREST endpoint
    internal enum Server1 {
        /// Supabase PostgREST endpoint
        ///
        /// - Parameters:
        ///   - baseUrl:
        internal static func url(baseUrl: Swift.String = "") throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "{baseUrl}",
                variables: [
                    .init(
                        name: "baseUrl",
                        value: baseUrl
                    )
                ]
            )
        }
    }
    /// Supabase PostgREST endpoint
    ///
    /// - Parameters:
    ///   - baseUrl:
    @available(*, deprecated, renamed: "Servers.Server1.url")
    internal static func server1(baseUrl: Swift.String = "") throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "{baseUrl}",
            variables: [
                .init(
                    name: "baseUrl",
                    value: baseUrl
                )
            ]
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
internal enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/PostgRESTError`.
        internal struct PostgRESTError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PostgRESTError/message`.
            internal var message: Swift.String?
            /// - Remark: Generated from `#/components/schemas/PostgRESTError/code`.
            internal var code: Swift.String?
            /// - Remark: Generated from `#/components/schemas/PostgRESTError/details`.
            internal var details: Swift.String?
            /// - Remark: Generated from `#/components/schemas/PostgRESTError/hint`.
            internal var hint: Swift.String?
            /// Creates a new `PostgRESTError`.
            ///
            /// - Parameters:
            ///   - message:
            ///   - code:
            ///   - details:
            ///   - hint:
            internal init(
                message: Swift.String? = nil,
                code: Swift.String? = nil,
                details: Swift.String? = nil,
                hint: Swift.String? = nil
            ) {
                self.message = message
                self.code = code
                self.details = details
                self.hint = hint
            }
            internal enum CodingKeys: String, CodingKey {
                case message
                case code
                case details
                case hint
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    internal enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    internal enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    internal enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    internal enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
internal enum Operations {
    /// - Remark: HTTP `POST /rpc/{functionName}`.
    /// - Remark: Generated from `#/paths//rpc/{functionName}/post(RpcOperations_rpc)`.
    internal enum RpcOperations_rpc {
        internal static let id: Swift.String = "RpcOperations_rpc"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/path/functionName`.
                internal var functionName: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - functionName:
                internal init(functionName: Swift.String) {
                    self.functionName = functionName
                }
            }
            internal var path: Operations.RpcOperations_rpc.Input.Path
            /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/query`.
            internal struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/query/params`.
                internal struct paramsPayload: Codable, Hashable, Sendable {
                    /// A container of undocumented properties.
                    internal var additionalProperties: [String: Swift.String]
                    /// Creates a new `paramsPayload`.
                    ///
                    /// - Parameters:
                    ///   - additionalProperties: A container of undocumented properties.
                    internal init(additionalProperties: [String: Swift.String] = .init()) {
                        self.additionalProperties = additionalProperties
                    }
                    internal init(from decoder: any Swift.Decoder) throws {
                        additionalProperties = try decoder.decodeAdditionalProperties(knownKeys: [])
                    }
                    internal func encode(to encoder: any Swift.Encoder) throws {
                        try encoder.encodeAdditionalProperties(additionalProperties)
                    }
                }
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/query/params`.
                internal var params: Operations.RpcOperations_rpc.Input.Query.paramsPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - params:
                internal init(params: Operations.RpcOperations_rpc.Input.Query.paramsPayload? = nil) {
                    self.params = params
                }
            }
            internal var query: Operations.RpcOperations_rpc.Input.Query
            /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/header/Prefer`.
                internal var Prefer: Swift.String?
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/header/Content-Profile`.
                internal var Content_hyphen_Profile: Swift.String?
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/header/Accept-Profile`.
                internal var Accept_hyphen_Profile: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.RpcOperations_rpc.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Prefer:
                ///   - Content_hyphen_Profile:
                ///   - Accept_hyphen_Profile:
                ///   - accept:
                internal init(
                    Prefer: Swift.String? = nil,
                    Content_hyphen_Profile: Swift.String? = nil,
                    Accept_hyphen_Profile: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.RpcOperations_rpc.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Prefer = Prefer
                    self.Content_hyphen_Profile = Content_hyphen_Profile
                    self.Accept_hyphen_Profile = Accept_hyphen_Profile
                    self.accept = accept
                }
            }
            internal var headers: Operations.RpcOperations_rpc.Input.Headers
            /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/requestBody/content/application\/json`.
                case json(OpenAPIRuntime.OpenAPIValueContainer)
            }
            internal var body: Operations.RpcOperations_rpc.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.RpcOperations_rpc.Input.Path,
                query: Operations.RpcOperations_rpc.Input.Query = .init(),
                headers: Operations.RpcOperations_rpc.Input.Headers = .init(),
                body: Operations.RpcOperations_rpc.Input.Body
            ) {
                self.path = path
                self.query = query
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.RpcOperations_rpc.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.RpcOperations_rpc.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//rpc/{functionName}/post(RpcOperations_rpc)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.RpcOperations_rpc.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.RpcOperations_rpc.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/rpc/{functionName}/POST/responses/default/content/application\/json`.
                    case json(Components.Schemas.PostgRESTError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.PostgRESTError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.RpcOperations_rpc.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.RpcOperations_rpc.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//rpc/{functionName}/post(RpcOperations_rpc)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.RpcOperations_rpc.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.RpcOperations_rpc.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `GET /{table}`.
    /// - Remark: Generated from `#/paths//{table}/get(TableOperations_from)`.
    internal enum TableOperations_from {
        internal static let id: Swift.String = "TableOperations_from"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/{table}/GET/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/GET/path/table`.
                internal var table: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - table:
                internal init(table: Swift.String) {
                    self.table = table
                }
            }
            internal var path: Operations.TableOperations_from.Input.Path
            /// - Remark: Generated from `#/paths/{table}/GET/query`.
            internal struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/GET/query/params`.
                internal struct paramsPayload: Codable, Hashable, Sendable {
                    /// A container of undocumented properties.
                    internal var additionalProperties: [String: Swift.String]
                    /// Creates a new `paramsPayload`.
                    ///
                    /// - Parameters:
                    ///   - additionalProperties: A container of undocumented properties.
                    internal init(additionalProperties: [String: Swift.String] = .init()) {
                        self.additionalProperties = additionalProperties
                    }
                    internal init(from decoder: any Swift.Decoder) throws {
                        additionalProperties = try decoder.decodeAdditionalProperties(knownKeys: [])
                    }
                    internal func encode(to encoder: any Swift.Encoder) throws {
                        try encoder.encodeAdditionalProperties(additionalProperties)
                    }
                }
                /// - Remark: Generated from `#/paths/{table}/GET/query/params`.
                internal var params: Operations.TableOperations_from.Input.Query.paramsPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - params:
                internal init(params: Operations.TableOperations_from.Input.Query.paramsPayload? = nil) {
                    self.params = params
                }
            }
            internal var query: Operations.TableOperations_from.Input.Query
            /// - Remark: Generated from `#/paths/{table}/GET/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/GET/header/Range`.
                internal var Range: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/GET/header/Prefer`.
                internal var Prefer: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/GET/header/Accept-Profile`.
                internal var Accept_hyphen_Profile: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_from.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Range:
                ///   - Prefer:
                ///   - Accept_hyphen_Profile:
                ///   - accept:
                internal init(
                    Range: Swift.String? = nil,
                    Prefer: Swift.String? = nil,
                    Accept_hyphen_Profile: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_from.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Range = Range
                    self.Prefer = Prefer
                    self.Accept_hyphen_Profile = Accept_hyphen_Profile
                    self.accept = accept
                }
            }
            internal var headers: Operations.TableOperations_from.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            internal init(
                path: Operations.TableOperations_from.Input.Path,
                query: Operations.TableOperations_from.Input.Query = .init(),
                headers: Operations.TableOperations_from.Input.Headers = .init()
            ) {
                self.path = path
                self.query = query
                self.headers = headers
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/GET/responses/200/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/GET/responses/200/headers/Content-Range`.
                    internal var Content_hyphen_Range: Swift.String?
                    /// - Remark: Generated from `#/paths/{table}/GET/responses/200/headers/Preference-Applied`.
                    internal var Preference_hyphen_Applied: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - Content_hyphen_Range:
                    ///   - Preference_hyphen_Applied:
                    internal init(
                        Content_hyphen_Range: Swift.String? = nil,
                        Preference_hyphen_Applied: Swift.String? = nil
                    ) {
                        self.Content_hyphen_Range = Content_hyphen_Range
                        self.Preference_hyphen_Applied = Preference_hyphen_Applied
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.TableOperations_from.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/{table}/GET/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/GET/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_from.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.TableOperations_from.Output.Ok.Headers = .init(),
                    body: Operations.TableOperations_from.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//{table}/get(TableOperations_from)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.TableOperations_from.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.TableOperations_from.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/GET/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/GET/responses/default/content/application\/json`.
                    case json(Components.Schemas.PostgRESTError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.PostgRESTError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_from.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.TableOperations_from.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//{table}/get(TableOperations_from)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.TableOperations_from.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.TableOperations_from.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /{table}`.
    /// - Remark: Generated from `#/paths//{table}/post(TableOperations_insert)`.
    internal enum TableOperations_insert {
        internal static let id: Swift.String = "TableOperations_insert"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/{table}/POST/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/POST/path/table`.
                internal var table: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - table:
                internal init(table: Swift.String) {
                    self.table = table
                }
            }
            internal var path: Operations.TableOperations_insert.Input.Path
            /// - Remark: Generated from `#/paths/{table}/POST/query`.
            internal struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/POST/query/params`.
                internal struct paramsPayload: Codable, Hashable, Sendable {
                    /// A container of undocumented properties.
                    internal var additionalProperties: [String: Swift.String]
                    /// Creates a new `paramsPayload`.
                    ///
                    /// - Parameters:
                    ///   - additionalProperties: A container of undocumented properties.
                    internal init(additionalProperties: [String: Swift.String] = .init()) {
                        self.additionalProperties = additionalProperties
                    }
                    internal init(from decoder: any Swift.Decoder) throws {
                        additionalProperties = try decoder.decodeAdditionalProperties(knownKeys: [])
                    }
                    internal func encode(to encoder: any Swift.Encoder) throws {
                        try encoder.encodeAdditionalProperties(additionalProperties)
                    }
                }
                /// - Remark: Generated from `#/paths/{table}/POST/query/params`.
                internal var params: Operations.TableOperations_insert.Input.Query.paramsPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - params:
                internal init(params: Operations.TableOperations_insert.Input.Query.paramsPayload? = nil) {
                    self.params = params
                }
            }
            internal var query: Operations.TableOperations_insert.Input.Query
            /// - Remark: Generated from `#/paths/{table}/POST/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/POST/header/Prefer`.
                internal var Prefer: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/POST/header/Content-Profile`.
                internal var Content_hyphen_Profile: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/POST/header/Accept-Profile`.
                internal var Accept_hyphen_Profile: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_insert.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Prefer:
                ///   - Content_hyphen_Profile:
                ///   - Accept_hyphen_Profile:
                ///   - accept:
                internal init(
                    Prefer: Swift.String? = nil,
                    Content_hyphen_Profile: Swift.String? = nil,
                    Accept_hyphen_Profile: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_insert.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Prefer = Prefer
                    self.Content_hyphen_Profile = Content_hyphen_Profile
                    self.Accept_hyphen_Profile = Accept_hyphen_Profile
                    self.accept = accept
                }
            }
            internal var headers: Operations.TableOperations_insert.Input.Headers
            /// - Remark: Generated from `#/paths/{table}/POST/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/POST/requestBody/content/application\/json`.
                case json(OpenAPIRuntime.OpenAPIValueContainer)
            }
            internal var body: Operations.TableOperations_insert.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.TableOperations_insert.Input.Path,
                query: Operations.TableOperations_insert.Input.Query = .init(),
                headers: Operations.TableOperations_insert.Input.Headers = .init(),
                body: Operations.TableOperations_insert.Input.Body
            ) {
                self.path = path
                self.query = query
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/POST/responses/201/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/POST/responses/201/headers/Content-Range`.
                    internal var Content_hyphen_Range: Swift.String?
                    /// - Remark: Generated from `#/paths/{table}/POST/responses/201/headers/Preference-Applied`.
                    internal var Preference_hyphen_Applied: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - Content_hyphen_Range:
                    ///   - Preference_hyphen_Applied:
                    internal init(
                        Content_hyphen_Range: Swift.String? = nil,
                        Preference_hyphen_Applied: Swift.String? = nil
                    ) {
                        self.Content_hyphen_Range = Content_hyphen_Range
                        self.Preference_hyphen_Applied = Preference_hyphen_Applied
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.TableOperations_insert.Output.Created.Headers
                /// - Remark: Generated from `#/paths/{table}/POST/responses/201/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/POST/responses/201/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_insert.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.TableOperations_insert.Output.Created.Headers = .init(),
                    body: Operations.TableOperations_insert.Output.Created.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// The request has succeeded and a new resource has been created as a result.
            ///
            /// - Remark: Generated from `#/paths//{table}/post(TableOperations_insert)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.TableOperations_insert.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            internal var created: Operations.TableOperations_insert.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/POST/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/POST/responses/default/content/application\/json`.
                    case json(Components.Schemas.PostgRESTError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.PostgRESTError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_insert.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.TableOperations_insert.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//{table}/post(TableOperations_insert)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.TableOperations_insert.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.TableOperations_insert.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `PATCH /{table}`.
    /// - Remark: Generated from `#/paths//{table}/patch(TableOperations_update)`.
    internal enum TableOperations_update {
        internal static let id: Swift.String = "TableOperations_update"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/{table}/PATCH/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PATCH/path/table`.
                internal var table: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - table:
                internal init(table: Swift.String) {
                    self.table = table
                }
            }
            internal var path: Operations.TableOperations_update.Input.Path
            /// - Remark: Generated from `#/paths/{table}/PATCH/query`.
            internal struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PATCH/query/params`.
                internal struct paramsPayload: Codable, Hashable, Sendable {
                    /// A container of undocumented properties.
                    internal var additionalProperties: [String: Swift.String]
                    /// Creates a new `paramsPayload`.
                    ///
                    /// - Parameters:
                    ///   - additionalProperties: A container of undocumented properties.
                    internal init(additionalProperties: [String: Swift.String] = .init()) {
                        self.additionalProperties = additionalProperties
                    }
                    internal init(from decoder: any Swift.Decoder) throws {
                        additionalProperties = try decoder.decodeAdditionalProperties(knownKeys: [])
                    }
                    internal func encode(to encoder: any Swift.Encoder) throws {
                        try encoder.encodeAdditionalProperties(additionalProperties)
                    }
                }
                /// - Remark: Generated from `#/paths/{table}/PATCH/query/params`.
                internal var params: Operations.TableOperations_update.Input.Query.paramsPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - params:
                internal init(params: Operations.TableOperations_update.Input.Query.paramsPayload? = nil) {
                    self.params = params
                }
            }
            internal var query: Operations.TableOperations_update.Input.Query
            /// - Remark: Generated from `#/paths/{table}/PATCH/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PATCH/header/Prefer`.
                internal var Prefer: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/PATCH/header/Content-Profile`.
                internal var Content_hyphen_Profile: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/PATCH/header/Accept-Profile`.
                internal var Accept_hyphen_Profile: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_update.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Prefer:
                ///   - Content_hyphen_Profile:
                ///   - Accept_hyphen_Profile:
                ///   - accept:
                internal init(
                    Prefer: Swift.String? = nil,
                    Content_hyphen_Profile: Swift.String? = nil,
                    Accept_hyphen_Profile: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_update.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Prefer = Prefer
                    self.Content_hyphen_Profile = Content_hyphen_Profile
                    self.Accept_hyphen_Profile = Accept_hyphen_Profile
                    self.accept = accept
                }
            }
            internal var headers: Operations.TableOperations_update.Input.Headers
            /// - Remark: Generated from `#/paths/{table}/PATCH/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PATCH/requestBody/content/application\/json`.
                case json(OpenAPIRuntime.OpenAPIValueContainer)
            }
            internal var body: Operations.TableOperations_update.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.TableOperations_update.Input.Path,
                query: Operations.TableOperations_update.Input.Query = .init(),
                headers: Operations.TableOperations_update.Input.Headers = .init(),
                body: Operations.TableOperations_update.Input.Body
            ) {
                self.path = path
                self.query = query
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PATCH/responses/200/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/PATCH/responses/200/headers/Content-Range`.
                    internal var Content_hyphen_Range: Swift.String?
                    /// - Remark: Generated from `#/paths/{table}/PATCH/responses/200/headers/Preference-Applied`.
                    internal var Preference_hyphen_Applied: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - Content_hyphen_Range:
                    ///   - Preference_hyphen_Applied:
                    internal init(
                        Content_hyphen_Range: Swift.String? = nil,
                        Preference_hyphen_Applied: Swift.String? = nil
                    ) {
                        self.Content_hyphen_Range = Content_hyphen_Range
                        self.Preference_hyphen_Applied = Preference_hyphen_Applied
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.TableOperations_update.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/{table}/PATCH/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/PATCH/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_update.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.TableOperations_update.Output.Ok.Headers = .init(),
                    body: Operations.TableOperations_update.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//{table}/patch(TableOperations_update)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.TableOperations_update.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.TableOperations_update.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PATCH/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/PATCH/responses/default/content/application\/json`.
                    case json(Components.Schemas.PostgRESTError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.PostgRESTError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_update.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.TableOperations_update.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//{table}/patch(TableOperations_update)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.TableOperations_update.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.TableOperations_update.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `PUT /{table}`.
    /// - Remark: Generated from `#/paths//{table}/put(TableOperations_upsert)`.
    internal enum TableOperations_upsert {
        internal static let id: Swift.String = "TableOperations_upsert"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/{table}/PUT/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PUT/path/table`.
                internal var table: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - table:
                internal init(table: Swift.String) {
                    self.table = table
                }
            }
            internal var path: Operations.TableOperations_upsert.Input.Path
            /// - Remark: Generated from `#/paths/{table}/PUT/query`.
            internal struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PUT/query/params`.
                internal struct paramsPayload: Codable, Hashable, Sendable {
                    /// A container of undocumented properties.
                    internal var additionalProperties: [String: Swift.String]
                    /// Creates a new `paramsPayload`.
                    ///
                    /// - Parameters:
                    ///   - additionalProperties: A container of undocumented properties.
                    internal init(additionalProperties: [String: Swift.String] = .init()) {
                        self.additionalProperties = additionalProperties
                    }
                    internal init(from decoder: any Swift.Decoder) throws {
                        additionalProperties = try decoder.decodeAdditionalProperties(knownKeys: [])
                    }
                    internal func encode(to encoder: any Swift.Encoder) throws {
                        try encoder.encodeAdditionalProperties(additionalProperties)
                    }
                }
                /// - Remark: Generated from `#/paths/{table}/PUT/query/params`.
                internal var params: Operations.TableOperations_upsert.Input.Query.paramsPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - params:
                internal init(params: Operations.TableOperations_upsert.Input.Query.paramsPayload? = nil) {
                    self.params = params
                }
            }
            internal var query: Operations.TableOperations_upsert.Input.Query
            /// - Remark: Generated from `#/paths/{table}/PUT/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PUT/header/Prefer`.
                internal var Prefer: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/PUT/header/Content-Profile`.
                internal var Content_hyphen_Profile: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/PUT/header/Accept-Profile`.
                internal var Accept_hyphen_Profile: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_upsert.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Prefer:
                ///   - Content_hyphen_Profile:
                ///   - Accept_hyphen_Profile:
                ///   - accept:
                internal init(
                    Prefer: Swift.String? = nil,
                    Content_hyphen_Profile: Swift.String? = nil,
                    Accept_hyphen_Profile: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_upsert.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Prefer = Prefer
                    self.Content_hyphen_Profile = Content_hyphen_Profile
                    self.Accept_hyphen_Profile = Accept_hyphen_Profile
                    self.accept = accept
                }
            }
            internal var headers: Operations.TableOperations_upsert.Input.Headers
            /// - Remark: Generated from `#/paths/{table}/PUT/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PUT/requestBody/content/application\/json`.
                case json(OpenAPIRuntime.OpenAPIValueContainer)
            }
            internal var body: Operations.TableOperations_upsert.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            ///   - body:
            internal init(
                path: Operations.TableOperations_upsert.Input.Path,
                query: Operations.TableOperations_upsert.Input.Query = .init(),
                headers: Operations.TableOperations_upsert.Input.Headers = .init(),
                body: Operations.TableOperations_upsert.Input.Body
            ) {
                self.path = path
                self.query = query
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PUT/responses/200/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/PUT/responses/200/headers/Content-Range`.
                    internal var Content_hyphen_Range: Swift.String?
                    /// - Remark: Generated from `#/paths/{table}/PUT/responses/200/headers/Preference-Applied`.
                    internal var Preference_hyphen_Applied: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - Content_hyphen_Range:
                    ///   - Preference_hyphen_Applied:
                    internal init(
                        Content_hyphen_Range: Swift.String? = nil,
                        Preference_hyphen_Applied: Swift.String? = nil
                    ) {
                        self.Content_hyphen_Range = Content_hyphen_Range
                        self.Preference_hyphen_Applied = Preference_hyphen_Applied
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.TableOperations_upsert.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/{table}/PUT/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/PUT/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_upsert.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.TableOperations_upsert.Output.Ok.Headers = .init(),
                    body: Operations.TableOperations_upsert.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//{table}/put(TableOperations_upsert)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.TableOperations_upsert.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.TableOperations_upsert.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/PUT/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/PUT/responses/default/content/application\/json`.
                    case json(Components.Schemas.PostgRESTError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.PostgRESTError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_upsert.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.TableOperations_upsert.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//{table}/put(TableOperations_upsert)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.TableOperations_upsert.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.TableOperations_upsert.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `DELETE /{table}`.
    /// - Remark: Generated from `#/paths//{table}/delete(TableOperations_deleteRows)`.
    internal enum TableOperations_deleteRows {
        internal static let id: Swift.String = "TableOperations_deleteRows"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/{table}/DELETE/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/DELETE/path/table`.
                internal var table: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - table:
                internal init(table: Swift.String) {
                    self.table = table
                }
            }
            internal var path: Operations.TableOperations_deleteRows.Input.Path
            /// - Remark: Generated from `#/paths/{table}/DELETE/query`.
            internal struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/DELETE/query/params`.
                internal struct paramsPayload: Codable, Hashable, Sendable {
                    /// A container of undocumented properties.
                    internal var additionalProperties: [String: Swift.String]
                    /// Creates a new `paramsPayload`.
                    ///
                    /// - Parameters:
                    ///   - additionalProperties: A container of undocumented properties.
                    internal init(additionalProperties: [String: Swift.String] = .init()) {
                        self.additionalProperties = additionalProperties
                    }
                    internal init(from decoder: any Swift.Decoder) throws {
                        additionalProperties = try decoder.decodeAdditionalProperties(knownKeys: [])
                    }
                    internal func encode(to encoder: any Swift.Encoder) throws {
                        try encoder.encodeAdditionalProperties(additionalProperties)
                    }
                }
                /// - Remark: Generated from `#/paths/{table}/DELETE/query/params`.
                internal var params: Operations.TableOperations_deleteRows.Input.Query.paramsPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - params:
                internal init(params: Operations.TableOperations_deleteRows.Input.Query.paramsPayload? = nil) {
                    self.params = params
                }
            }
            internal var query: Operations.TableOperations_deleteRows.Input.Query
            /// - Remark: Generated from `#/paths/{table}/DELETE/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/DELETE/header/Prefer`.
                internal var Prefer: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/DELETE/header/Content-Profile`.
                internal var Content_hyphen_Profile: Swift.String?
                /// - Remark: Generated from `#/paths/{table}/DELETE/header/Accept-Profile`.
                internal var Accept_hyphen_Profile: Swift.String?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_deleteRows.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Prefer:
                ///   - Content_hyphen_Profile:
                ///   - Accept_hyphen_Profile:
                ///   - accept:
                internal init(
                    Prefer: Swift.String? = nil,
                    Content_hyphen_Profile: Swift.String? = nil,
                    Accept_hyphen_Profile: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.TableOperations_deleteRows.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Prefer = Prefer
                    self.Content_hyphen_Profile = Content_hyphen_Profile
                    self.Accept_hyphen_Profile = Accept_hyphen_Profile
                    self.accept = accept
                }
            }
            internal var headers: Operations.TableOperations_deleteRows.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            internal init(
                path: Operations.TableOperations_deleteRows.Input.Path,
                query: Operations.TableOperations_deleteRows.Input.Query = .init(),
                headers: Operations.TableOperations_deleteRows.Input.Headers = .init()
            ) {
                self.path = path
                self.query = query
                self.headers = headers
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/DELETE/responses/200/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/DELETE/responses/200/headers/Content-Range`.
                    internal var Content_hyphen_Range: Swift.String?
                    /// - Remark: Generated from `#/paths/{table}/DELETE/responses/200/headers/Preference-Applied`.
                    internal var Preference_hyphen_Applied: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - Content_hyphen_Range:
                    ///   - Preference_hyphen_Applied:
                    internal init(
                        Content_hyphen_Range: Swift.String? = nil,
                        Preference_hyphen_Applied: Swift.String? = nil
                    ) {
                        self.Content_hyphen_Range = Content_hyphen_Range
                        self.Preference_hyphen_Applied = Preference_hyphen_Applied
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.TableOperations_deleteRows.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/{table}/DELETE/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/DELETE/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_deleteRows.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.TableOperations_deleteRows.Output.Ok.Headers = .init(),
                    body: Operations.TableOperations_deleteRows.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// The request has succeeded.
            ///
            /// - Remark: Generated from `#/paths//{table}/delete(TableOperations_deleteRows)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.TableOperations_deleteRows.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.TableOperations_deleteRows.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/{table}/DELETE/responses/default/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/{table}/DELETE/responses/default/content/application\/json`.
                    case json(Components.Schemas.PostgRESTError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.PostgRESTError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.TableOperations_deleteRows.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.TableOperations_deleteRows.Output.Default.Body) {
                    self.body = body
                }
            }
            /// An unexpected error response.
            ///
            /// - Remark: Generated from `#/paths//{table}/delete(TableOperations_deleteRows)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.TableOperations_deleteRows.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            internal var `default`: Operations.TableOperations_deleteRows.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
