//
//  EndToEndTests.swift
//

import Foundation
import InlineSnapshotTesting
import OpenAPIKit30
import Testing

@testable import OpenAPICodegenCore

@Suite
struct EndToEndTests {

  @Test
  func generatesModelsAndClientFromAMinimalStorageLikeSpec() throws {
    let json = """
      {
        "openapi": "3.0.3",
        "info": {"title": "Storage", "version": "1.0.0"},
        "paths": {
          "/bucket/{bucketId}": {
            "get": {
              "operationId": "getBucket",
              "parameters": [
                {"name": "bucketId", "in": "path", "required": true, "schema": {"type": "string"}}
              ],
              "responses": {
                "200": {
                  "description": "ok",
                  "content": {
                    "application/json": {"schema": {"$ref": "#/components/schemas/bucketSchema"}}
                  }
                },
                "404": {
                  "description": "not found",
                  "content": {
                    "application/json": {"schema": {"$ref": "#/components/schemas/errorSchema"}}
                  }
                }
              }
            }
          }
        },
        "components": {
          "schemas": {
            "bucketSchema": {
              "type": "object",
              "required": ["id", "public"],
              "properties": {
                "id": {"type": "string"},
                "public": {"type": "boolean"}
              }
            },
            "errorSchema": {
              "type": "object",
              "required": ["message"],
              "properties": {"message": {"type": "string"}}
            }
          }
        }
      }
      """
    let document = try JSONDecoder().decode(OpenAPI.Document.self, from: Data(json.utf8))
    let irDocument = try OpenAPIParsing.parseDocument(document)

    let models = SwiftEmitter.emitModels(irDocument)
    let client = SwiftEmitter.emitClient(irDocument, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: models, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      public struct BucketSchema: Codable, Sendable, Hashable {
        public var id: String
        public var `public`: Bool

        enum CodingKeys: String, CodingKey {
          case id = "id"
          case `public` = "public"
        }
      }

      public struct ErrorSchema: Codable, Sendable, Hashable, APIError {
        public var message: String

        enum CodingKeys: String, CodingKey {
          case message = "message"
        }
      }

      """
    }
    assertInlineSnapshot(of: client, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      public struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        public init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        public func getBucket(bucketId: String) async throws -> BucketSchema {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [404: ErrorSchema.self])
          return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
        }
      }
      """#
    }
  }
}
