//
//  EndToEndTests.swift
//

import Foundation
import InlineSnapshotTesting
import OpenAPIKit
import Testing

@testable import OpenAPICodegenCore

@Suite
struct EndToEndTests {

  @Test
  func generatesModelsAndClientFromAMinimalStorageLikeSpec() throws {
    let json = """
      {
        "openapi": "3.1.0",
        "info": {"title": "Storage", "version": "1.0.0"},
        "paths": {
          "/bucket/{bucketId}": {
            "get": {
              "operationId": "getBucket",
              "parameters": [
                {"name": "bucketId", "in": "path", "required": true, "schema": {"type": "string"}}
              ],
              "responses": {
                "200": {
                  "description": "ok",
                  "content": {
                    "application/json": {"schema": {"$ref": "#/components/schemas/bucketSchema"}}
                  }
                },
                "404": {
                  "description": "not found",
                  "content": {
                    "application/json": {"schema": {"$ref": "#/components/schemas/errorSchema"}}
                  }
                }
              }
            }
          }
        },
        "components": {
          "schemas": {
            "bucketSchema": {
              "type": "object",
              "required": ["id", "public"],
              "properties": {
                "id": {"type": "string"},
                "public": {"type": "boolean"}
              }
            },
            "errorSchema": {
              "type": "object",
              "required": ["message"],
              "properties": {"message": {"type": "string"}}
            }
          }
        }
      }
      """
    let document = try JSONDecoder().decode(OpenAPI.Document.self, from: Data(json.utf8))
    let irDocument = try OpenAPIParsing.parseDocument(document)

    let models = SwiftEmitter.emitModels(irDocument, namespace: "TestAPI")
    let client = SwiftEmitter.emitClient(
      irDocument, namespace: "TestAPI")

    assertInlineSnapshot(of: models, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal enum TestAPI {
        internal struct BucketSchema: Codable, Sendable, Hashable {
          internal var id: String
          internal var `public`: Bool

          enum CodingKeys: String, CodingKey {
            case id = "id"
            case `public` = "public"
          }
        }

        internal struct ErrorSchema: Codable, Sendable, Hashable, APIError {
          internal var message: String

          enum CodingKeys: String, CodingKey {
            case message = "message"
          }
        }

      }
      """
    }
    assertInlineSnapshot(of: client, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal extension TestAPI {
        internal struct Client: Sendable {
          private let baseURL: URL
          private let transport: any HTTPTransport

          internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
            self.baseURL = baseURL
            self.transport = transport
          }

          internal func getBucket(bucketId: String) async throws -> BucketSchema {
            let builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
            let response = try await transport.send(try builder.build())
            try response.checkStatus(errorTypes: [404: ErrorSchema.self])
            return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
          }
        }
      }
      """#
    }
  }
}
