// Code generated by openapi-codegen. DO NOT EDIT.

import Foundation
import HTTPRuntime

internal struct AuthSchema: Codable, Sendable, Hashable {
  internal var authorization: String

  enum CodingKeys: String, CodingKey {
    case authorization = "authorization"
  }
}

internal struct BucketCreateRequestBody: Codable, Sendable, Hashable {
  internal var allowedMimeTypes: [String]?
  internal var fileSizeLimit: BucketCreateRequestBodyFileSizeLimit?
  internal var id: String?
  internal var name: String
  internal var `public`: Bool?
  internal var type: BucketCreateRequestBodyType?

  enum CodingKeys: String, CodingKey {
    case allowedMimeTypes = "allowed_mime_types"
    case fileSizeLimit = "file_size_limit"
    case id = "id"
    case name = "name"
    case `public` = "public"
    case type = "type"
  }
}

internal enum BucketCreateRequestBodyFileSizeLimit: Codable, Sendable, Hashable {
  case integer(Int)
  case string(String)

  internal init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let value = try? container.decode(Int.self) {
      self = .integer(value)
      return
    }
    if let value = try? container.decode(String.self) {
      self = .string(value)
      return
    }
    throw DecodingError.typeMismatch(
      BucketCreateRequestBodyFileSizeLimit.self,
      DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "no matching case")
    )
  }

  internal func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .integer(let value): try container.encode(value)
    case .string(let value): try container.encode(value)
    }
  }
}

internal enum BucketCreateRequestBodyType: String, Codable, Sendable, Hashable {
  case STANDARD = "STANDARD"
  case ANALYTICS = "ANALYTICS"
}

internal struct BucketCreateResponse200: Codable, Sendable, Hashable {
  internal var name: String

  enum CodingKeys: String, CodingKey {
    case name = "name"
  }
}

internal struct BucketDeleteResponse200: Codable, Sendable, Hashable {
  internal var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal struct BucketEmptyResponse200: Codable, Sendable, Hashable {
  internal var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal enum BucketListHeadSortColumn: String, Codable, Sendable, Hashable {
  case id = "id"
  case name = "name"
  case createdAt = "created_at"
  case updatedAt = "updated_at"
}

internal enum BucketListHeadSortOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

internal enum BucketListSortColumn: String, Codable, Sendable, Hashable {
  case id = "id"
  case name = "name"
  case createdAt = "created_at"
  case updatedAt = "updated_at"
}

internal enum BucketListSortOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

internal struct BucketSchema: Codable, Sendable, Hashable {
  internal var allowedMimeTypes: [String]?
  internal var createdAt: String?
  internal var fileSizeLimit: Int?
  internal var id: String
  internal var name: String
  internal var owner: String?
  internal var ownerId: String?
  internal var `public`: Bool?
  internal var type: BucketSchemaType?
  internal var updatedAt: String?

  enum CodingKeys: String, CodingKey {
    case allowedMimeTypes = "allowed_mime_types"
    case createdAt = "created_at"
    case fileSizeLimit = "file_size_limit"
    case id = "id"
    case name = "name"
    case owner = "owner"
    case ownerId = "owner_id"
    case `public` = "public"
    case type = "type"
    case updatedAt = "updated_at"
  }
}

internal enum BucketSchemaType: String, Codable, Sendable, Hashable {
  case STANDARD = "STANDARD"
  case ANALYTICS = "ANALYTICS"
}

internal struct BucketUpdateRequestBody: Codable, Sendable, Hashable {
  internal var allowedMimeTypes: [String]?
  internal var fileSizeLimit: BucketUpdateRequestBodyFileSizeLimit?
  internal var `public`: Bool?

  enum CodingKeys: String, CodingKey {
    case allowedMimeTypes = "allowed_mime_types"
    case fileSizeLimit = "file_size_limit"
    case `public` = "public"
  }
}

internal enum BucketUpdateRequestBodyFileSizeLimit: Codable, Sendable, Hashable {
  case integer(Int)
  case string(String)

  internal init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let value = try? container.decode(Int.self) {
      self = .integer(value)
      return
    }
    if let value = try? container.decode(String.self) {
      self = .string(value)
      return
    }
    throw DecodingError.typeMismatch(
      BucketUpdateRequestBodyFileSizeLimit.self,
      DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "no matching case")
    )
  }

  internal func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .integer(let value): try container.encode(value)
    case .string(let value): try container.encode(value)
    }
  }
}

internal struct BucketUpdateResponse200: Codable, Sendable, Hashable {
  internal var message: String

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal struct CdnPurgeBucketCacheResponse200: Codable, Sendable, Hashable {
  internal var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal struct CdnPurgeObjectCacheResponse200: Codable, Sendable, Hashable {
  internal var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal struct CdnPurgeTenantCacheResponse200: Codable, Sendable, Hashable {
  internal var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal struct ErrorSchema: Codable, Sendable, Hashable, APIError {
  internal var error: String
  internal var message: String
  internal var statusCode: String

  enum CodingKeys: String, CodingKey {
    case error = "error"
    case message = "message"
    case statusCode = "statusCode"
  }
}

internal struct ObjectCopyRequestBody: Codable, Sendable, Hashable {
  internal var bucketId: String
  internal var copyMetadata: Bool?
  internal var destinationBucket: String?
  internal var destinationKey: String
  internal var metadata: ObjectCopyRequestBodyMetadata?
  internal var sourceKey: String

  enum CodingKeys: String, CodingKey {
    case bucketId = "bucketId"
    case copyMetadata = "copyMetadata"
    case destinationBucket = "destinationBucket"
    case destinationKey = "destinationKey"
    case metadata = "metadata"
    case sourceKey = "sourceKey"
  }
}

internal struct ObjectCopyRequestBodyMetadata: Codable, Sendable, Hashable {
  internal var cacheControl: String?
  internal var mimetype: String?

  enum CodingKeys: String, CodingKey {
    case cacheControl = "cacheControl"
    case mimetype = "mimetype"
  }
}

internal struct ObjectCopyResponse200: Codable, Sendable, Hashable {
  internal var Id: String?
  internal var Key: String
  internal var bucketId: String?
  internal var buckets: BucketSchema?
  internal var createdAt: String?
  internal var id: String?
  internal var lastAccessedAt: String?
  internal var metadata: [String: JSONValue]?
  internal var name: String?
  internal var owner: String?
  internal var ownerId: String?
  internal var updatedAt: String?
  internal var userMetadata: [String: JSONValue]?
  internal var version: String?

  enum CodingKeys: String, CodingKey {
    case Id = "Id"
    case Key = "Key"
    case bucketId = "bucket_id"
    case buckets = "buckets"
    case createdAt = "created_at"
    case id = "id"
    case lastAccessedAt = "last_accessed_at"
    case metadata = "metadata"
    case name = "name"
    case owner = "owner"
    case ownerId = "owner_id"
    case updatedAt = "updated_at"
    case userMetadata = "user_metadata"
    case version = "version"
  }
}

internal struct ObjectDeleteManyRequestBody: Codable, Sendable, Hashable {
  internal var prefixes: [String]

  enum CodingKeys: String, CodingKey {
    case prefixes = "prefixes"
  }
}

internal struct ObjectDeleteResponse200: Codable, Sendable, Hashable {
  internal var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal enum ObjectGetAuthenticatedInfo2Format: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectGetAuthenticatedInfo2Resize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectGetAuthenticatedInfoGetFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectGetAuthenticatedInfoGetResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectGetAuthenticatedInfoHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectGetAuthenticatedInfoHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectGetAuthenticatedInfoFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectGetAuthenticatedInfoResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectHeadAuthenticatedInfoHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectHeadAuthenticatedInfoHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectHeadAuthenticatedInfoFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectHeadAuthenticatedInfoResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectInfoPublicGetFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectInfoPublicGetResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum ObjectInfoPublicFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectInfoPublicResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal struct ObjectListV2RequestBody: Codable, Sendable, Hashable {
  internal var cursor: String?
  internal var limit: Int?
  internal var prefix: String?
  internal var sortBy: ObjectListV2RequestBodySortBy?
  internal var withDelimiter: Bool?

  enum CodingKeys: String, CodingKey {
    case cursor = "cursor"
    case limit = "limit"
    case prefix = "prefix"
    case sortBy = "sortBy"
    case withDelimiter = "with_delimiter"
  }
}

internal struct ObjectListV2RequestBodySortBy: Codable, Sendable, Hashable {
  internal var column: ObjectListV2RequestBodySortByColumn
  internal var order: ObjectListV2RequestBodySortByOrder?

  enum CodingKeys: String, CodingKey {
    case column = "column"
    case order = "order"
  }
}

internal enum ObjectListV2RequestBodySortByColumn: String, Codable, Sendable, Hashable {
  case name = "name"
  case updatedAt = "updated_at"
  case createdAt = "created_at"
}

internal enum ObjectListV2RequestBodySortByOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

internal struct ObjectListRequestBody: Codable, Sendable, Hashable {
  internal var limit: Int?
  internal var offset: Int?
  internal var prefix: String
  internal var search: String?
  internal var sortBy: ObjectListRequestBodySortBy?

  enum CodingKeys: String, CodingKey {
    case limit = "limit"
    case offset = "offset"
    case prefix = "prefix"
    case search = "search"
    case sortBy = "sortBy"
  }
}

internal struct ObjectListRequestBodySortBy: Codable, Sendable, Hashable {
  internal var column: ObjectListRequestBodySortByColumn
  internal var order: ObjectListRequestBodySortByOrder?

  enum CodingKeys: String, CodingKey {
    case column = "column"
    case order = "order"
  }
}

internal enum ObjectListRequestBodySortByColumn: String, Codable, Sendable, Hashable {
  case name = "name"
  case updatedAt = "updated_at"
  case createdAt = "created_at"
  case lastAccessedAt = "last_accessed_at"
}

internal enum ObjectListRequestBodySortByOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

internal struct ObjectMoveRequestBody: Codable, Sendable, Hashable {
  internal var bucketId: String
  internal var destinationBucket: String?
  internal var destinationKey: String
  internal var sourceKey: String

  enum CodingKeys: String, CodingKey {
    case bucketId = "bucketId"
    case destinationBucket = "destinationBucket"
    case destinationKey = "destinationKey"
    case sourceKey = "sourceKey"
  }
}

internal struct ObjectMoveResponse200: Codable, Sendable, Hashable {
  internal var message: String

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

internal struct ObjectSchema: Codable, Sendable, Hashable {
  internal var bucketId: String?
  internal var buckets: BucketSchema?
  internal var createdAt: String?
  internal var id: String?
  internal var lastAccessedAt: String?
  internal var metadata: [String: JSONValue]?
  internal var name: String
  internal var owner: String?
  internal var ownerId: String?
  internal var updatedAt: String?
  internal var userMetadata: [String: JSONValue]?
  internal var version: String?

  enum CodingKeys: String, CodingKey {
    case bucketId = "bucket_id"
    case buckets = "buckets"
    case createdAt = "created_at"
    case id = "id"
    case lastAccessedAt = "last_accessed_at"
    case metadata = "metadata"
    case name = "name"
    case owner = "owner"
    case ownerId = "owner_id"
    case updatedAt = "updated_at"
    case userMetadata = "user_metadata"
    case version = "version"
  }
}

internal struct ObjectSignManyRequestBody: Codable, Sendable, Hashable {
  internal var expiresIn: Int
  internal var paths: [String]

  enum CodingKeys: String, CodingKey {
    case expiresIn = "expiresIn"
    case paths = "paths"
  }
}

internal struct ObjectSignManyResponse200Item: Codable, Sendable, Hashable {
  internal var error: String?
  internal var path: String
  internal var signedURL: String?

  enum CodingKeys: String, CodingKey {
    case error = "error"
    case path = "path"
    case signedURL = "signedURL"
  }
}

internal struct ObjectSignUploadUrlResponse200: Codable, Sendable, Hashable {
  internal var token: String?
  internal var url: String

  enum CodingKeys: String, CodingKey {
    case token = "token"
    case url = "url"
  }
}

internal struct ObjectSignRequestBody: Codable, Sendable, Hashable {
  internal var expiresIn: Int
  internal var transform: ObjectSignRequestBodyTransform?

  enum CodingKeys: String, CodingKey {
    case expiresIn = "expiresIn"
    case transform = "transform"
  }
}

internal struct ObjectSignRequestBodyTransform: Codable, Sendable, Hashable {
  internal var format: ObjectSignRequestBodyTransformFormat?
  internal var height: Int?
  internal var quality: Int?
  internal var resize: ObjectSignRequestBodyTransformResize?
  internal var width: Int?

  enum CodingKeys: String, CodingKey {
    case format = "format"
    case height = "height"
    case quality = "quality"
    case resize = "resize"
    case width = "width"
  }
}

internal enum ObjectSignRequestBodyTransformFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum ObjectSignRequestBodyTransformResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal struct ObjectSignResponse200: Codable, Sendable, Hashable {
  internal var signedURL: String

  enum CodingKeys: String, CodingKey {
    case signedURL = "signedURL"
  }
}

internal struct ObjectUploadSignedResponse200: Codable, Sendable, Hashable {
  internal var Key: String

  enum CodingKeys: String, CodingKey {
    case Key = "Key"
  }
}

internal struct ObjectUploadUpdateResponse200: Codable, Sendable, Hashable {
  internal var Id: String?
  internal var Key: String

  enum CodingKeys: String, CodingKey {
    case Id = "Id"
    case Key = "Key"
  }
}

internal struct ObjectUploadResponse200: Codable, Sendable, Hashable {
  internal var Id: String?
  internal var Key: String

  enum CodingKeys: String, CodingKey {
    case Id = "Id"
    case Key = "Key"
  }
}

internal enum RenderImageAuthenticatedHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum RenderImageAuthenticatedHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum RenderImageAuthenticatedFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum RenderImageAuthenticatedResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum RenderImagePublicHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum RenderImagePublicHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

internal enum RenderImagePublicFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

internal enum RenderImagePublicResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}
