// Code generated by openapi-codegen. DO NOT EDIT.

import Foundation
public import HTTPRuntime

public struct AuthSchema: Codable, Sendable, Hashable {
  public var authorization: String

  enum CodingKeys: String, CodingKey {
    case authorization = "authorization"
  }
}

public struct BucketCreateRequestBody: Codable, Sendable, Hashable {
  public var allowedMimeTypes: [String]?
  public var fileSizeLimit: BucketCreateRequestBodyFileSizeLimit?
  public var id: String?
  public var name: String
  public var `public`: Bool?
  public var type: BucketCreateRequestBodyType?

  enum CodingKeys: String, CodingKey {
    case allowedMimeTypes = "allowed_mime_types"
    case fileSizeLimit = "file_size_limit"
    case id = "id"
    case name = "name"
    case `public` = "public"
    case type = "type"
  }
}

public enum BucketCreateRequestBodyFileSizeLimit: Codable, Sendable, Hashable {
  case integer(Int)
  case string(String)

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let value = try? container.decode(Int.self) {
      self = .integer(value)
      return
    }
    if let value = try? container.decode(String.self) {
      self = .string(value)
      return
    }
    throw DecodingError.typeMismatch(
      BucketCreateRequestBodyFileSizeLimit.self,
      DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "no matching case")
    )
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .integer(let value): try container.encode(value)
    case .string(let value): try container.encode(value)
    }
  }
}

public enum BucketCreateRequestBodyType: String, Codable, Sendable, Hashable {
  case STANDARD = "STANDARD"
  case ANALYTICS = "ANALYTICS"
}

public struct BucketCreateResponse200: Codable, Sendable, Hashable {
  public var name: String

  enum CodingKeys: String, CodingKey {
    case name = "name"
  }
}

public struct BucketDeleteResponse200: Codable, Sendable, Hashable {
  public var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public struct BucketEmptyResponse200: Codable, Sendable, Hashable {
  public var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public enum BucketListHeadSortColumn: String, Codable, Sendable, Hashable {
  case id = "id"
  case name = "name"
  case createdAt = "created_at"
  case updatedAt = "updated_at"
}

public enum BucketListHeadSortOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

public enum BucketListSortColumn: String, Codable, Sendable, Hashable {
  case id = "id"
  case name = "name"
  case createdAt = "created_at"
  case updatedAt = "updated_at"
}

public enum BucketListSortOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

public struct BucketSchema: Codable, Sendable, Hashable {
  public var allowedMimeTypes: [String]?
  public var createdAt: String?
  public var fileSizeLimit: Int?
  public var id: String
  public var name: String
  public var owner: String?
  public var ownerId: String?
  public var `public`: Bool?
  public var type: BucketSchemaType?
  public var updatedAt: String?

  enum CodingKeys: String, CodingKey {
    case allowedMimeTypes = "allowed_mime_types"
    case createdAt = "created_at"
    case fileSizeLimit = "file_size_limit"
    case id = "id"
    case name = "name"
    case owner = "owner"
    case ownerId = "owner_id"
    case `public` = "public"
    case type = "type"
    case updatedAt = "updated_at"
  }
}

public enum BucketSchemaType: String, Codable, Sendable, Hashable {
  case STANDARD = "STANDARD"
  case ANALYTICS = "ANALYTICS"
}

public struct BucketUpdateRequestBody: Codable, Sendable, Hashable {
  public var allowedMimeTypes: [String]?
  public var fileSizeLimit: BucketUpdateRequestBodyFileSizeLimit?
  public var `public`: Bool?

  enum CodingKeys: String, CodingKey {
    case allowedMimeTypes = "allowed_mime_types"
    case fileSizeLimit = "file_size_limit"
    case `public` = "public"
  }
}

public enum BucketUpdateRequestBodyFileSizeLimit: Codable, Sendable, Hashable {
  case integer(Int)
  case string(String)

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let value = try? container.decode(Int.self) {
      self = .integer(value)
      return
    }
    if let value = try? container.decode(String.self) {
      self = .string(value)
      return
    }
    throw DecodingError.typeMismatch(
      BucketUpdateRequestBodyFileSizeLimit.self,
      DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "no matching case")
    )
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .integer(let value): try container.encode(value)
    case .string(let value): try container.encode(value)
    }
  }
}

public struct BucketUpdateResponse200: Codable, Sendable, Hashable {
  public var message: String

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public struct CdnPurgeBucketCacheResponse200: Codable, Sendable, Hashable {
  public var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public struct CdnPurgeObjectCacheResponse200: Codable, Sendable, Hashable {
  public var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public struct CdnPurgeTenantCacheResponse200: Codable, Sendable, Hashable {
  public var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public struct ErrorSchema: Codable, Sendable, Hashable, APIError {
  public var error: String
  public var message: String
  public var statusCode: String

  enum CodingKeys: String, CodingKey {
    case error = "error"
    case message = "message"
    case statusCode = "statusCode"
  }
}

public struct ObjectCopyRequestBody: Codable, Sendable, Hashable {
  public var bucketId: String
  public var copyMetadata: Bool?
  public var destinationBucket: String?
  public var destinationKey: String
  public var metadata: ObjectCopyRequestBodyMetadata?
  public var sourceKey: String

  enum CodingKeys: String, CodingKey {
    case bucketId = "bucketId"
    case copyMetadata = "copyMetadata"
    case destinationBucket = "destinationBucket"
    case destinationKey = "destinationKey"
    case metadata = "metadata"
    case sourceKey = "sourceKey"
  }
}

public struct ObjectCopyRequestBodyMetadata: Codable, Sendable, Hashable {
  public var cacheControl: String?
  public var mimetype: String?

  enum CodingKeys: String, CodingKey {
    case cacheControl = "cacheControl"
    case mimetype = "mimetype"
  }
}

public struct ObjectCopyResponse200: Codable, Sendable, Hashable {
  public var Id: String?
  public var Key: String
  public var bucketId: String?
  public var buckets: BucketSchema?
  public var createdAt: String?
  public var id: String?
  public var lastAccessedAt: String?
  public var metadata: [String: JSONValue]?
  public var name: String?
  public var owner: String?
  public var ownerId: String?
  public var updatedAt: String?
  public var userMetadata: [String: JSONValue]?
  public var version: String?

  enum CodingKeys: String, CodingKey {
    case Id = "Id"
    case Key = "Key"
    case bucketId = "bucket_id"
    case buckets = "buckets"
    case createdAt = "created_at"
    case id = "id"
    case lastAccessedAt = "last_accessed_at"
    case metadata = "metadata"
    case name = "name"
    case owner = "owner"
    case ownerId = "owner_id"
    case updatedAt = "updated_at"
    case userMetadata = "user_metadata"
    case version = "version"
  }
}

public struct ObjectDeleteManyRequestBody: Codable, Sendable, Hashable {
  public var prefixes: [String]

  enum CodingKeys: String, CodingKey {
    case prefixes = "prefixes"
  }
}

public struct ObjectDeleteResponse200: Codable, Sendable, Hashable {
  public var message: String?

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public enum ObjectGetAuthenticatedInfo2Format: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectGetAuthenticatedInfo2Resize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectGetAuthenticatedInfoGetFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectGetAuthenticatedInfoGetResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectGetAuthenticatedInfoHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectGetAuthenticatedInfoHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectGetAuthenticatedInfoFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectGetAuthenticatedInfoResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectHeadAuthenticatedInfoHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectHeadAuthenticatedInfoHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectHeadAuthenticatedInfoFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectHeadAuthenticatedInfoResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectInfoPublicGetFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectInfoPublicGetResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum ObjectInfoPublicFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectInfoPublicResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public struct ObjectListV2RequestBody: Codable, Sendable, Hashable {
  public var cursor: String?
  public var limit: Int?
  public var prefix: String?
  public var sortBy: ObjectListV2RequestBodySortBy?
  public var withDelimiter: Bool?

  enum CodingKeys: String, CodingKey {
    case cursor = "cursor"
    case limit = "limit"
    case prefix = "prefix"
    case sortBy = "sortBy"
    case withDelimiter = "with_delimiter"
  }
}

public struct ObjectListV2RequestBodySortBy: Codable, Sendable, Hashable {
  public var column: ObjectListV2RequestBodySortByColumn
  public var order: ObjectListV2RequestBodySortByOrder?

  enum CodingKeys: String, CodingKey {
    case column = "column"
    case order = "order"
  }
}

public enum ObjectListV2RequestBodySortByColumn: String, Codable, Sendable, Hashable {
  case name = "name"
  case updatedAt = "updated_at"
  case createdAt = "created_at"
}

public enum ObjectListV2RequestBodySortByOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

public struct ObjectListRequestBody: Codable, Sendable, Hashable {
  public var limit: Int?
  public var offset: Int?
  public var prefix: String
  public var search: String?
  public var sortBy: ObjectListRequestBodySortBy?

  enum CodingKeys: String, CodingKey {
    case limit = "limit"
    case offset = "offset"
    case prefix = "prefix"
    case search = "search"
    case sortBy = "sortBy"
  }
}

public struct ObjectListRequestBodySortBy: Codable, Sendable, Hashable {
  public var column: ObjectListRequestBodySortByColumn
  public var order: ObjectListRequestBodySortByOrder?

  enum CodingKeys: String, CodingKey {
    case column = "column"
    case order = "order"
  }
}

public enum ObjectListRequestBodySortByColumn: String, Codable, Sendable, Hashable {
  case name = "name"
  case updatedAt = "updated_at"
  case createdAt = "created_at"
  case lastAccessedAt = "last_accessed_at"
}

public enum ObjectListRequestBodySortByOrder: String, Codable, Sendable, Hashable {
  case asc = "asc"
  case desc = "desc"
}

public struct ObjectMoveRequestBody: Codable, Sendable, Hashable {
  public var bucketId: String
  public var destinationBucket: String?
  public var destinationKey: String
  public var sourceKey: String

  enum CodingKeys: String, CodingKey {
    case bucketId = "bucketId"
    case destinationBucket = "destinationBucket"
    case destinationKey = "destinationKey"
    case sourceKey = "sourceKey"
  }
}

public struct ObjectMoveResponse200: Codable, Sendable, Hashable {
  public var message: String

  enum CodingKeys: String, CodingKey {
    case message = "message"
  }
}

public struct ObjectSchema: Codable, Sendable, Hashable {
  public var bucketId: String?
  public var buckets: BucketSchema?
  public var createdAt: String?
  public var id: String?
  public var lastAccessedAt: String?
  public var metadata: [String: JSONValue]?
  public var name: String
  public var owner: String?
  public var ownerId: String?
  public var updatedAt: String?
  public var userMetadata: [String: JSONValue]?
  public var version: String?

  enum CodingKeys: String, CodingKey {
    case bucketId = "bucket_id"
    case buckets = "buckets"
    case createdAt = "created_at"
    case id = "id"
    case lastAccessedAt = "last_accessed_at"
    case metadata = "metadata"
    case name = "name"
    case owner = "owner"
    case ownerId = "owner_id"
    case updatedAt = "updated_at"
    case userMetadata = "user_metadata"
    case version = "version"
  }
}

public struct ObjectSignManyRequestBody: Codable, Sendable, Hashable {
  public var expiresIn: Int
  public var paths: [String]

  enum CodingKeys: String, CodingKey {
    case expiresIn = "expiresIn"
    case paths = "paths"
  }
}

public struct ObjectSignManyResponse200Item: Codable, Sendable, Hashable {
  public var error: String?
  public var path: String
  public var signedURL: String?

  enum CodingKeys: String, CodingKey {
    case error = "error"
    case path = "path"
    case signedURL = "signedURL"
  }
}

public struct ObjectSignUploadUrlResponse200: Codable, Sendable, Hashable {
  public var token: String?
  public var url: String

  enum CodingKeys: String, CodingKey {
    case token = "token"
    case url = "url"
  }
}

public struct ObjectSignRequestBody: Codable, Sendable, Hashable {
  public var expiresIn: Int
  public var transform: ObjectSignRequestBodyTransform?

  enum CodingKeys: String, CodingKey {
    case expiresIn = "expiresIn"
    case transform = "transform"
  }
}

public struct ObjectSignRequestBodyTransform: Codable, Sendable, Hashable {
  public var format: ObjectSignRequestBodyTransformFormat?
  public var height: Int?
  public var quality: Int?
  public var resize: ObjectSignRequestBodyTransformResize?
  public var width: Int?

  enum CodingKeys: String, CodingKey {
    case format = "format"
    case height = "height"
    case quality = "quality"
    case resize = "resize"
    case width = "width"
  }
}

public enum ObjectSignRequestBodyTransformFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum ObjectSignRequestBodyTransformResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public struct ObjectSignResponse200: Codable, Sendable, Hashable {
  public var signedURL: String

  enum CodingKeys: String, CodingKey {
    case signedURL = "signedURL"
  }
}

public struct ObjectUploadSignedResponse200: Codable, Sendable, Hashable {
  public var Key: String

  enum CodingKeys: String, CodingKey {
    case Key = "Key"
  }
}

public struct ObjectUploadUpdateResponse200: Codable, Sendable, Hashable {
  public var Id: String?
  public var Key: String

  enum CodingKeys: String, CodingKey {
    case Id = "Id"
    case Key = "Key"
  }
}

public struct ObjectUploadResponse200: Codable, Sendable, Hashable {
  public var Id: String?
  public var Key: String

  enum CodingKeys: String, CodingKey {
    case Id = "Id"
    case Key = "Key"
  }
}

public enum RenderImageAuthenticatedHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum RenderImageAuthenticatedHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum RenderImageAuthenticatedFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum RenderImageAuthenticatedResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum RenderImagePublicHeadFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum RenderImagePublicHeadResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}

public enum RenderImagePublicFormat: String, Codable, Sendable, Hashable {
  case origin = "origin"
  case avif = "avif"
  case webp = "webp"
}

public enum RenderImagePublicResize: String, Codable, Sendable, Hashable {
  case cover = "cover"
  case contain = "contain"
  case fill = "fill"
}
