// Code generated by openapi-codegen. DO NOT EDIT.

public import Foundation
public import HTTPRuntime

public struct StorageOpenAPIClient: Sendable {
  private let baseURL: URL
  private let transport: any HTTPTransport

  public init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
    self.baseURL = baseURL
    self.transport = transport
  }

  public func bucketCreate(payload: BucketCreateRequestBody) async throws -> BucketCreateResponse200
  {
    var builder = HTTPRequestBuilder(method: .post, baseURL: baseURL, path: "/bucket")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(BucketCreateResponse200.self, from: response.body)
  }

  public func bucketDelete(bucketId: String) async throws -> BucketDeleteResponse200 {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(BucketDeleteResponse200.self, from: response.body)
  }

  public func bucketEmpty(bucketId: String) async throws -> BucketEmptyResponse200 {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))/empty")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(BucketEmptyResponse200.self, from: response.body)
  }

  public func bucketGet(bucketId: String) async throws -> BucketSchema {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
  }

  public func bucketGetHead(bucketId: String) async throws -> BucketSchema {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
  }

  public func bucketList(
    limit: Int? = nil, offset: Int? = nil, search: String? = nil,
    sortColumn: BucketListSortColumn? = nil, sortOrder: BucketListSortOrder? = nil
  ) async throws -> [BucketSchema] {
    var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket")
    builder.addQuery("limit", limit.map(String.init))
    builder.addQuery("offset", offset.map(String.init))
    builder.addQuery("search", search)
    builder.addQuery("sortColumn", sortColumn?.rawValue)
    builder.addQuery("sortOrder", sortOrder?.rawValue)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([BucketSchema].self, from: response.body)
  }

  public func bucketListHead(
    limit: Int? = nil, offset: Int? = nil, search: String? = nil,
    sortColumn: BucketListHeadSortColumn? = nil, sortOrder: BucketListHeadSortOrder? = nil
  ) async throws -> [BucketSchema] {
    var builder = HTTPRequestBuilder(method: .head, baseURL: baseURL, path: "/bucket")
    builder.addQuery("limit", limit.map(String.init))
    builder.addQuery("offset", offset.map(String.init))
    builder.addQuery("search", search)
    builder.addQuery("sortColumn", sortColumn?.rawValue)
    builder.addQuery("sortOrder", sortOrder?.rawValue)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([BucketSchema].self, from: response.body)
  }

  public func bucketUpdate(bucketId: String, payload: BucketUpdateRequestBody) async throws
    -> BucketUpdateResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .put, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(BucketUpdateResponse200.self, from: response.body)
  }

  public func cdnPurgeBucketCache(bucketName: String, transformations: Bool? = nil) async throws
    -> CdnPurgeBucketCacheResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL, path: "/cdn/\(PathEncoding.segment(bucketName))")
    builder.addQuery("transformations", transformations.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(CdnPurgeBucketCacheResponse200.self, from: response.body)
  }

  public func cdnPurgeObjectCache(
    bucketName: String, wildcard: String, transformations: Bool? = nil
  ) async throws -> CdnPurgeObjectCacheResponse200 {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL,
      path: "/cdn/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("transformations", transformations.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(CdnPurgeObjectCacheResponse200.self, from: response.body)
  }

  public func cdnPurgeTenantCache(transformations: Bool? = nil) async throws
    -> CdnPurgeTenantCacheResponse200
  {
    var builder = HTTPRequestBuilder(method: .delete, baseURL: baseURL, path: "/cdn/")
    builder.addQuery("transformations", transformations.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(CdnPurgeTenantCacheResponse200.self, from: response.body)
  }

  public func healthcheck() async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/health")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func healthcheckHead() async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(method: .head, baseURL: baseURL, path: "/health")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func objectCopy(payload: ObjectCopyRequestBody) async throws -> ObjectCopyResponse200 {
    var builder = HTTPRequestBuilder(method: .post, baseURL: baseURL, path: "/object/copy")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectCopyResponse200.self, from: response.body)
  }

  public func objectDelete(bucketName: String, wildcard: String) async throws
    -> ObjectDeleteResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL,
      path: "/object/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectDeleteResponse200.self, from: response.body)
  }

  public func objectDeleteMany(bucketName: String, payload: ObjectDeleteManyRequestBody)
    async throws -> [ObjectSchema]
  {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL, path: "/object/\(PathEncoding.segment(bucketName))")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([ObjectSchema].self, from: response.body)
  }

  public func objectGetAuthenticated(bucketName: String, wildcard: String, download: String? = nil)
    async throws
  {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path:
        "/object/authenticated/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("download", download)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectGetAuthenticatedGet(bucketName: String, wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path: "/object/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectGetAuthenticatedInfo(
    bucketName: String, wildcard: String, format: ObjectGetAuthenticatedInfoFormat? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectGetAuthenticatedInfoResize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path:
        "/object/info/authenticated/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectGetAuthenticatedInfo2(
    bucketName: String, wildcard: String, format: ObjectGetAuthenticatedInfo2Format? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectGetAuthenticatedInfo2Resize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path: "/object/info/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectGetAuthenticatedInfoGet(
    bucketName: String, wildcard: String, format: ObjectGetAuthenticatedInfoGetFormat? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectGetAuthenticatedInfoGetResize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path: "/object/info/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectGetAuthenticatedInfoHead(
    bucketName: String, wildcard: String, format: ObjectGetAuthenticatedInfoHeadFormat? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectGetAuthenticatedInfoHeadResize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path:
        "/object/info/authenticated/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectGetPublic(bucketName: String, wildcard: String, download: String? = nil)
    async throws
  {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path: "/object/public/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("download", download)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func objectGetSigned(
    bucketName: String, token: String, wildcard: String, download: String? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path: "/object/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("token", token)
    builder.addQuery("download", download)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func objectGetSignedHead(
    bucketName: String, token: String, wildcard: String, download: String? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path: "/object/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("token", token)
    builder.addQuery("download", download)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func objectHeadAuthenticatedInfo(
    bucketName: String, wildcard: String, format: ObjectHeadAuthenticatedInfoFormat? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectHeadAuthenticatedInfoResize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path:
        "/object/authenticated/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectHeadAuthenticatedInfoHead(
    bucketName: String, wildcard: String, format: ObjectHeadAuthenticatedInfoHeadFormat? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectHeadAuthenticatedInfoHeadResize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path: "/object/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func objectInfoPublic(
    bucketName: String, wildcard: String, format: ObjectInfoPublicFormat? = nil, height: Int? = nil,
    quality: Int? = nil, resize: ObjectInfoPublicResize? = nil, width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path: "/object/public/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func objectInfoPublicGet(
    bucketName: String, wildcard: String, format: ObjectInfoPublicGetFormat? = nil,
    height: Int? = nil, quality: Int? = nil, resize: ObjectInfoPublicGetResize? = nil,
    width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path:
        "/object/info/public/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func objectList(bucketName: String, payload: ObjectListRequestBody) async throws
    -> [ObjectSchema]
  {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL, path: "/object/list/\(PathEncoding.segment(bucketName))")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([ObjectSchema].self, from: response.body)
  }

  public func objectListV2(bucketName: String, payload: ObjectListV2RequestBody) async throws
    -> [String: JSONValue]
  {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL, path: "/object/list-v2/\(PathEncoding.segment(bucketName))")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func objectMove(payload: ObjectMoveRequestBody) async throws -> ObjectMoveResponse200 {
    var builder = HTTPRequestBuilder(method: .post, baseURL: baseURL, path: "/object/move")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectMoveResponse200.self, from: response.body)
  }

  public func objectSign(bucketName: String, wildcard: String, payload: ObjectSignRequestBody)
    async throws -> ObjectSignResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL,
      path: "/object/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectSignResponse200.self, from: response.body)
  }

  public func objectSignMany(bucketName: String, payload: ObjectSignManyRequestBody) async throws
    -> [ObjectSignManyResponse200Item]
  {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL, path: "/object/sign/\(PathEncoding.segment(bucketName))")
    builder.setHeader("Content-Type", "application/json")
    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([ObjectSignManyResponse200Item].self, from: response.body)
  }

  public func objectSignUploadUrl(bucketName: String, wildcard: String) async throws
    -> ObjectSignUploadUrlResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL,
      path:
        "/object/upload/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectSignUploadUrlResponse200.self, from: response.body)
  }

  public func objectUpload(bucketName: String, wildcard: String) async throws
    -> ObjectUploadResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL,
      path: "/object/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectUploadResponse200.self, from: response.body)
  }

  public func objectUploadSigned(bucketName: String, token: String, wildcard: String) async throws
    -> ObjectUploadSignedResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .put, baseURL: baseURL,
      path:
        "/object/upload/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("token", token)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
    return try JSONCoding.decoder.decode(ObjectUploadSignedResponse200.self, from: response.body)
  }

  public func objectUploadUpdate(bucketName: String, wildcard: String) async throws
    -> ObjectUploadUpdateResponse200
  {
    var builder = HTTPRequestBuilder(
      method: .put, baseURL: baseURL,
      path: "/object/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode(ObjectUploadUpdateResponse200.self, from: response.body)
  }

  public func renderImageAuthenticated(
    bucketName: String, wildcard: String, download: String? = nil,
    format: RenderImageAuthenticatedFormat? = nil, height: Int? = nil, quality: Int? = nil,
    resize: RenderImageAuthenticatedResize? = nil, width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path:
        "/render/image/authenticated/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("download", download)
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func renderImageAuthenticatedHead(
    bucketName: String, wildcard: String, download: String? = nil,
    format: RenderImageAuthenticatedHeadFormat? = nil, height: Int? = nil, quality: Int? = nil,
    resize: RenderImageAuthenticatedHeadResize? = nil, width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path:
        "/render/image/authenticated/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("download", download)
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
  }

  public func renderImagePublic(
    bucketName: String, wildcard: String, download: String? = nil,
    format: RenderImagePublicFormat? = nil, height: Int? = nil, quality: Int? = nil,
    resize: RenderImagePublicResize? = nil, width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path:
        "/render/image/public/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("download", download)
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func renderImagePublicHead(
    bucketName: String, wildcard: String, download: String? = nil,
    format: RenderImagePublicHeadFormat? = nil, height: Int? = nil, quality: Int? = nil,
    resize: RenderImagePublicHeadResize? = nil, width: Int? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path:
        "/render/image/public/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))"
    )
    builder.addQuery("download", download)
    builder.addQuery("format", format?.rawValue)
    builder.addQuery("height", height.map(String.init))
    builder.addQuery("quality", quality.map(String.init))
    builder.addQuery("resize", resize?.rawValue)
    builder.addQuery("width", width.map(String.init))
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func renderImageSign(
    bucketName: String, token: String, wildcard: String, download: String? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .get, baseURL: baseURL,
      path:
        "/render/image/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("token", token)
    builder.addQuery("download", download)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func renderImageSignHead(
    bucketName: String, token: String, wildcard: String, download: String? = nil
  ) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path:
        "/render/image/sign/\(PathEncoding.segment(bucketName))/\(PathEncoding.segment(wildcard))")
    builder.addQuery("token", token)
    builder.addQuery("download", download)
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusOptions() async throws {
    var builder = HTTPRequestBuilder(method: .options, baseURL: baseURL, path: "/upload/resumable/")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusOptionsOptions(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .options, baseURL: baseURL,
      path: "/upload/resumable/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusOptionsSigned() async throws {
    var builder = HTTPRequestBuilder(
      method: .options, baseURL: baseURL, path: "/upload/resumable/sign/")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusOptionsSignedOptions(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .options, baseURL: baseURL,
      path: "/upload/resumable/sign/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusUploadCreate() async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(method: .post, baseURL: baseURL, path: "/upload/resumable/")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func tusUploadCreatePost(wildcard: String) async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL, path: "/upload/resumable/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func tusUploadCreateSigned() async throws {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL, path: "/upload/resumable/sign/")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusUploadCreateSignedPost(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .post, baseURL: baseURL,
      path: "/upload/resumable/sign/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusUploadDelete(wildcard: String) async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL, path: "/upload/resumable/\(PathEncoding.segment(wildcard))"
    )
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func tusUploadDeleteSigned(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .delete, baseURL: baseURL,
      path: "/upload/resumable/sign/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusUploadGet(wildcard: String) async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL, path: "/upload/resumable/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func tusUploadGetSigned(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .head, baseURL: baseURL,
      path: "/upload/resumable/sign/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusUploadPart(wildcard: String) async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(
      method: .put, baseURL: baseURL, path: "/upload/resumable/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func tusUploadPartPatch(wildcard: String) async throws -> [String: JSONValue] {
    var builder = HTTPRequestBuilder(
      method: .patch, baseURL: baseURL, path: "/upload/resumable/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [403: ErrorSchema.self])
    return try JSONCoding.decoder.decode([String: JSONValue].self, from: response.body)
  }

  public func tusUploadPartSigned(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .put, baseURL: baseURL,
      path: "/upload/resumable/sign/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }

  public func tusUploadPartSignedPatch(wildcard: String) async throws {
    var builder = HTTPRequestBuilder(
      method: .patch, baseURL: baseURL,
      path: "/upload/resumable/sign/\(PathEncoding.segment(wildcard))")
    let response = try await transport.send(try builder.build())
    try response.checkStatus(errorTypes: [:])
  }
}
