//
//  SwiftEmitter.swift
//

enum SwiftEmitter {

  static func emitModels(_ document: IRDocument) -> String {
    let errorSchemaNames = self.errorSchemaNames(in: document)
    var lines: [String] = [
      "// Code generated by openapi-codegen. DO NOT EDIT.",
      "",
      "import Foundation",
      "import HTTPRuntime",
      "",
    ]
    for schema in document.schemas.sorted(by: { $0.name < $1.name }) {
      lines.append(emitSchema(schema, isError: errorSchemaNames.contains(schema.name)))
      lines.append("")
    }
    return lines.joined(separator: "\n")
  }

  static func errorSchemaNames(in document: IRDocument) -> Set<String> {
    var names: Set<String> = []
    for operation in document.operations {
      for response in operation.responses where response.isError {
        if case .json(.schemaRef(let name)) = response.body {
          names.insert(name)
        }
      }
    }
    return names
  }

  static func emitSchema(_ schema: IRSchema, isError: Bool) -> String {
    let typeName = SwiftNames.typeName(schema.name)
    switch schema.kind {
    case .object(let properties):
      return emitStruct(named: typeName, properties: properties, isError: isError)
    case .stringEnum(let cases):
      return emitStringEnum(named: typeName, cases: cases, isError: isError)
    }
  }

  static func emitStruct(named typeName: String, properties: [IRProperty], isError: Bool) -> String {
    let conformances = (["Codable", "Sendable", "Hashable"] + (isError ? ["APIError"] : []))
      .joined(separator: ", ")
    var lines = ["public struct \(typeName): \(conformances) {"]
    for property in properties {
      let name = SwiftNames.propertyName(property.name)
      let type = SwiftNames.typeReference(property.type, isOptional: property.isOptional)
      lines.append("  public var \(name): \(type)")
    }
    lines.append("")
    lines.append("  enum CodingKeys: String, CodingKey {")
    for property in properties {
      let name = SwiftNames.propertyName(property.name)
      lines.append("    case \(name) = \"\(property.name)\"")
    }
    lines.append("  }")
    lines.append("}")
    return lines.joined(separator: "\n")
  }

  static func emitStringEnum(named typeName: String, cases: [String], isError: Bool) -> String {
    let conformances = (["String", "Codable", "Sendable", "Hashable"] + (isError ? ["APIError"] : []))
      .joined(separator: ", ")
    var lines = ["public enum \(typeName): \(conformances) {"]
    for value in cases {
      lines.append("  case \(SwiftNames.propertyName(value)) = \"\(value)\"")
    }
    lines.append("}")
    return lines.joined(separator: "\n")
  }
}
