//
//  SwiftEmitter.swift
//

/// The access level generated declarations get. Defaults to the narrowest
/// (`.internal`) — callers opt into wider visibility explicitly rather than
/// generated code defaulting to `public`.
public enum AccessLevel: String, CaseIterable, Sendable {
  case `public`
  case package
  case `internal`
}

public enum SwiftEmitter {

  public static func emitModels(_ document: IRDocument, accessLevel: AccessLevel = .internal)
    -> String
  {
    let errorSchemaNames = self.errorSchemaNames(in: document)
    let importKeyword = accessLevel == .public ? "public import" : "import"
    var lines: [String] = [
      "// Code generated by openapi-codegen. DO NOT EDIT.",
      "",
      "import Foundation",
      "\(importKeyword) HTTPRuntime",
      "",
    ]
    for schema in document.schemas.sorted(by: { $0.name < $1.name }) {
      lines.append(
        emitSchema(
          schema, isError: errorSchemaNames.contains(schema.name), accessLevel: accessLevel)
      )
      lines.append("")
    }
    return lines.joined(separator: "\n")
  }

  static func errorSchemaNames(in document: IRDocument) -> Set<String> {
    var names: Set<String> = []
    for operation in document.operations {
      for response in operation.responses where response.isError {
        if case .json(.schemaRef(let name)) = response.body {
          names.insert(name)
        }
      }
    }
    return names
  }

  static func emitSchema(_ schema: IRSchema, isError: Bool, accessLevel: AccessLevel) -> String {
    let typeName = SwiftNames.typeName(schema.name)
    switch schema.kind {
    case .object(let properties):
      return emitStruct(
        named: typeName, properties: properties, isError: isError, accessLevel: accessLevel)
    case .stringEnum(let cases):
      return emitStringEnum(
        named: typeName, cases: cases, isError: isError, accessLevel: accessLevel)
    case .union(let cases):
      return emitUnion(named: typeName, cases: cases, isError: isError, accessLevel: accessLevel)
    }
  }

  static func emitStruct(
    named typeName: String, properties: [IRProperty], isError: Bool, accessLevel: AccessLevel
  ) -> String {
    let conformances = (["Codable", "Sendable", "Hashable"] + (isError ? ["APIError"] : []))
      .joined(separator: ", ")
    var lines = ["\(accessLevel.rawValue) struct \(typeName): \(conformances) {"]
    for property in properties {
      let name = SwiftNames.propertyName(property.name)
      let type = SwiftNames.typeReference(property.type, isOptional: property.isOptional)
      lines.append("  \(accessLevel.rawValue) var \(name): \(type)")
    }
    lines.append("")
    lines.append("  enum CodingKeys: String, CodingKey {")
    for property in properties {
      let name = SwiftNames.propertyName(property.name)
      lines.append("    case \(name) = \"\(property.name)\"")
    }
    lines.append("  }")
    lines.append("}")
    return lines.joined(separator: "\n")
  }

  static func emitStringEnum(
    named typeName: String, cases: [String], isError: Bool, accessLevel: AccessLevel
  ) -> String {
    let conformances =
      (["String", "Codable", "Sendable", "Hashable"] + (isError ? ["APIError"] : []))
      .joined(separator: ", ")
    var lines = ["\(accessLevel.rawValue) enum \(typeName): \(conformances) {"]
    for value in cases {
      lines.append("  case \(SwiftNames.propertyName(value)) = \"\(value)\"")
    }
    lines.append("}")
    return lines.joined(separator: "\n")
  }

  static func emitUnion(
    named typeName: String, cases: [IRUnionCase], isError: Bool, accessLevel: AccessLevel
  ) -> String {
    let conformances = (["Codable", "Sendable", "Hashable"] + (isError ? ["APIError"] : []))
      .joined(separator: ", ")
    var lines = ["\(accessLevel.rawValue) enum \(typeName): \(conformances) {"]
    for unionCase in cases {
      let caseName = SwiftNames.propertyName(unionCase.name)
      let typeRef = SwiftNames.typeReference(unionCase.type, isOptional: false)
      lines.append("  case \(caseName)(\(typeRef))")
    }
    lines.append("")
    lines.append("  \(accessLevel.rawValue) init(from decoder: any Decoder) throws {")
    lines.append("    let container = try decoder.singleValueContainer()")
    for unionCase in cases {
      let caseName = SwiftNames.propertyName(unionCase.name)
      let typeRef = SwiftNames.typeReference(unionCase.type, isOptional: false)
      lines.append("    if let value = try? container.decode(\(typeRef).self) {")
      lines.append("      self = .\(caseName)(value)")
      lines.append("      return")
      lines.append("    }")
    }
    lines.append("    throw DecodingError.typeMismatch(")
    lines.append("      \(typeName).self,")
    lines.append(
      "      DecodingError.Context(codingPath: decoder.codingPath, debugDescription: \"no matching case\")"
    )
    lines.append("    )")
    lines.append("  }")
    lines.append("")
    lines.append("  \(accessLevel.rawValue) func encode(to encoder: any Encoder) throws {")
    lines.append("    var container = encoder.singleValueContainer()")
    lines.append("    switch self {")
    for unionCase in cases {
      let caseName = SwiftNames.propertyName(unionCase.name)
      lines.append("    case .\(caseName)(let value): try container.encode(value)")
    }
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    return lines.joined(separator: "\n")
  }

  // MARK: - Client

  public static func emitClient(
    _ document: IRDocument, clientName: String, accessLevel: AccessLevel = .internal
  ) -> String {
    let errorSchemaNames = self.errorSchemaNames(in: document)
    let importKeyword = accessLevel == .public ? "public import" : "import"
    var lines: [String] = [
      "// Code generated by openapi-codegen. DO NOT EDIT.",
      "",
      "\(importKeyword) Foundation",
      "\(importKeyword) HTTPRuntime",
      "",
      "\(accessLevel.rawValue) struct \(clientName): Sendable {",
      "  private let baseURL: URL",
      "  private let transport: any HTTPTransport",
      "",
      "  \(accessLevel.rawValue) init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {",
      "    self.baseURL = baseURL",
      "    self.transport = transport",
      "  }",
    ]
    for operation in document.operations.sorted(by: { $0.operationId < $1.operationId }) {
      lines.append("")
      lines.append(
        contentsOf: emitOperation(
          operation, errorSchemaNames: errorSchemaNames, accessLevel: accessLevel))
    }
    lines.append("}")
    return lines.joined(separator: "\n")
  }

  static func emitOperation(
    _ operation: IROperation, errorSchemaNames: Set<String>, accessLevel: AccessLevel
  ) -> [String] {
    let methodName = SwiftNames.propertyName(operation.operationId)
    let parameters = operation.parameters.sorted { lhs, rhs in
      lhs.isOptional != rhs.isOptional ? !lhs.isOptional : lhs.name < rhs.name
    }
    var signatureParts = parameters.map { parameter -> String in
      let name = SwiftNames.propertyName(parameter.name)
      let type = SwiftNames.typeReference(parameter.type, isOptional: parameter.isOptional)
      return "\(name): \(type)\(parameter.isOptional ? " = nil" : "")"
    }
    if let requestBody = operation.requestBody {
      signatureParts.append(contentsOf: requestBodyParameters(requestBody))
    }
    let successResponse = operation.responses.first { !$0.isError }
    let returnType = returnTypeReference(for: successResponse)

    var lines: [String] = [
      "  \(accessLevel.rawValue) func \(methodName)(\(signatureParts.joined(separator: ", "))) async throws"
        + (returnType.map { " -> \($0)" } ?? "") + " {",
      "    var builder = HTTPRequestBuilder(method: .\(operation.method.rawValue), baseURL: baseURL, path: \"\(pathTemplate(operation))\")",
    ]
    for parameter in parameters where parameter.location == .query {
      lines.append(
        "    builder.addQuery(\"\(parameter.name)\", \(stringConversionExpression(parameter)))")
    }
    for parameter in parameters where parameter.location == .header {
      lines.append(
        "    builder.setHeader(\"\(parameter.name)\", \(stringConversionExpression(parameter)))")
    }
    if let requestBody = operation.requestBody {
      lines.append(contentsOf: requestBodyLines(requestBody))
    }
    if let successResponse, case .binary = successResponse.body {
      lines.append("    let stream = try await transport.stream(try builder.build())")
      lines.append("    guard stream.head.isSuccess else {")
      lines.append(
        "      throw HTTPError.unexpectedStatus(status: stream.head.status, body: Data())")
      lines.append("    }")
      lines.append("    return stream.body")
    } else {
      lines.append("    let response = try await transport.send(try builder.build())")
      lines.append(
        "    try response.checkStatus(errorTypes: \(errorTypesLiteral(operation, errorSchemaNames: errorSchemaNames)))"
      )
      if let successResponse, case .json(let type) = successResponse.body {
        let typeName = SwiftNames.typeReference(type, isOptional: false)
        lines.append(
          "    return try JSONCoding.decoder.decode(\(typeName).self, from: response.body)")
      }
    }
    lines.append("  }")
    return lines
  }

  static func pathTemplate(_ operation: IROperation) -> String {
    var result = operation.path
    for parameter in operation.parameters where parameter.location == .path {
      let name = SwiftNames.propertyName(parameter.name)
      let stringExpr = parameter.type == .string ? name : "String(\(name))"
      result = result.replacingOccurrences(
        of: "{\(parameter.name)}", with: "\\(PathEncoding.segment(\(stringExpr)))")
    }
    return result
  }

  static func stringConversionExpression(_ parameter: IRParameter) -> String {
    let name = SwiftNames.propertyName(parameter.name)
    if case .string = parameter.type { return name }
    // Schema-ref parameters are always emitted as `String`-backed enums
    // (see `emitStringEnum`), so `.rawValue` converts them — `String.init`
    // would be ambiguous between the enum's `RawRepresentable` conformance
    // and other `String` initializer overloads.
    if case .schemaRef = parameter.type {
      return parameter.isOptional ? "\(name)?.rawValue" : "\(name).rawValue"
    }
    if case .array(let element) = parameter.type {
      if case .string = element { return name }
      return parameter.isOptional ? "\(name)?.map(String.init)" : "\(name).map(String.init)"
    }
    return parameter.isOptional ? "\(name).map(String.init)" : "String(\(name))"
  }

  static func requestBodyParameters(_ requestBody: IRRequestBody) -> [String] {
    switch requestBody {
    case .json(let type):
      return ["payload: \(SwiftNames.typeReference(type, isOptional: false))"]
    case .multipart(let fields):
      return fields.map { field in
        let name = SwiftNames.propertyName(field.name)
        let type = field.isFile ? "URL" : SwiftNames.typeReference(field.type, isOptional: false)
        return "\(name): \(type)"
      }
    }
  }

  static func requestBodyLines(_ requestBody: IRRequestBody) -> [String] {
    switch requestBody {
    case .json:
      return [
        "    builder.setHeader(\"Content-Type\", \"application/json\")",
        "    builder.setBody(.data(try JSONCoding.encoder.encode(payload)))",
      ]
    case .multipart(let fields):
      var formDataExpression = "MultipartFormData()"
      for field in fields {
        let name = SwiftNames.propertyName(field.name)
        if field.isFile {
          formDataExpression +=
            "\n      .addFile(name: \"\(field.name)\", fileURL: \(name), fileName: \(name).lastPathComponent, mimeType: \"application/octet-stream\")"
        } else {
          formDataExpression +=
            "\n      .addText(name: \"\(field.name)\", value: String(describing: \(name)))"
        }
      }
      return [
        "    let formData = \(formDataExpression)",
        "    builder.setHeader(\"Content-Type\", formData.contentType)",
        "    builder.setBody(.multipart(formData))",
      ]
    }
  }

  static func returnTypeReference(for response: IRResponse?) -> String? {
    guard let response else { return nil }
    switch response.body {
    case .none: return nil
    case .json(let type): return SwiftNames.typeReference(type, isOptional: false)
    case .binary: return "AsyncThrowingStream<Data, any Error>"
    }
  }

  static func errorTypesLiteral(_ operation: IROperation, errorSchemaNames: Set<String>) -> String {
    var entries: [String] = []
    for response in operation.responses where response.isError {
      if case .json(.schemaRef(let name)) = response.body, errorSchemaNames.contains(name) {
        entries.append("\(response.statusCode): \(SwiftNames.typeName(name)).self")
      }
    }
    guard !entries.isEmpty else { return "[:]" }
    return "[\(entries.joined(separator: ", "))]"
  }
}
