//
//  ClientEmitterTests.swift
//

import InlineSnapshotTesting
import Testing

@testable import OpenAPICodegenCore

@Suite
struct ClientEmitterTests {

  @Test
  func emitsJSONRoundTripOperation() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "getBucket",
          method: .get,
          path: "/bucket/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: nil,
          responses: [
            IRResponse(statusCode: 200, isError: false, body: .json(.schemaRef("bucketSchema"))),
            IRResponse(statusCode: 404, isError: true, body: .json(.schemaRef("errorSchema"))),
          ]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        internal func getBucket(bucketId: String) async throws -> BucketSchema {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [404: ErrorSchema.self])
          return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
        }
      }
      """#
    }
  }

  @Test
  func emitsMultipartUploadOperation() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "createObject",
          method: .post,
          path: "/object/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: .multipart(fields: [
            IRMultipartField(name: "file", type: .string, isFile: true),
            IRMultipartField(name: "cacheControl", type: .string, isFile: false),
          ]),
          responses: [
            IRResponse(statusCode: 200, isError: false, body: .none)
          ]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        internal func createObject(bucketId: String, file: URL, cacheControl: String) async throws {
          var builder = HTTPRequestBuilder(method: .post, baseURL: baseURL, path: "/object/\(PathEncoding.segment(bucketId))")
          let formData = MultipartFormData()
            .addFile(name: "file", fileURL: file, fileName: file.lastPathComponent, mimeType: "application/octet-stream")
            .addText(name: "cacheControl", value: String(describing: cacheControl))
          builder.setHeader("Content-Type", formData.contentType)
          builder.setBody(.multipart(formData))
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [:])
        }
      }
      """#
    }
  }

  @Test
  func emitsBinaryDownloadOperation() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "download",
          method: .get,
          path: "/object/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: nil,
          responses: [IRResponse(statusCode: 200, isError: false, body: .binary)]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        internal func download(bucketId: String) async throws -> AsyncThrowingStream<Data, any Error> {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/object/\(PathEncoding.segment(bucketId))")
          let stream = try await transport.stream(try builder.build())
          guard stream.head.isSuccess else {
            throw HTTPError.unexpectedStatus(status: stream.head.status, body: Data())
          }
          return stream.body
        }
      }
      """#
    }
  }

  @Test
  func emitsSchemaRefQueryParameterUsingRawValue() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "listBuckets",
          method: .get,
          path: "/bucket",
          parameters: [
            IRParameter(
              name: "sortColumn", location: .query, type: .schemaRef("BucketListSortColumn"),
              isOptional: true)
          ],
          requestBody: nil,
          responses: [
            IRResponse(statusCode: 200, isError: false, body: .json(.schemaRef("bucketSchema")))
          ]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        internal func listBuckets(sortColumn: BucketListSortColumn? = nil) async throws -> BucketSchema {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket")
          builder.addQuery("sortColumn", sortColumn?.rawValue)
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [:])
          return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
        }
      }
      """
    }
  }

  @Test
  func emitsArrayQueryParameter() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "listItems",
          method: .get,
          path: "/items",
          parameters: [
            IRParameter(name: "tags", location: .query, type: .array(.string), isOptional: true)
          ],
          requestBody: nil,
          responses: [IRResponse(statusCode: 200, isError: false, body: .none)]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        internal func listItems(tags: [String]? = nil) async throws {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/items")
          builder.addQuery("tags", tags)
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [:])
        }
      }
      """
    }
  }

  @Test
  func emitsArrayOfIntegerQueryParameter() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "listItems",
          method: .get,
          path: "/items",
          parameters: [
            IRParameter(name: "ids", location: .query, type: .array(.integer), isOptional: true)
          ],
          requestBody: nil,
          responses: [IRResponse(statusCode: 200, isError: false, body: .none)]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        internal init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        internal func listItems(ids: [Int]? = nil) async throws {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/items")
          builder.addQuery("ids", ids?.map(String.init))
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [:])
        }
      }
      """
    }
  }

  @Test
  func emitsPublicAccessLevelWhenRequested() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "getBucket",
          method: .get,
          path: "/bucket/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: nil,
          responses: [IRResponse(statusCode: 200, isError: false, body: .none)]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(
      document, clientName: "StorageOpenAPIClient", accessLevel: .public)

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      public import Foundation
      public import HTTPRuntime

      public struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        public init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        public func getBucket(bucketId: String) async throws {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [:])
        }
      }
      """#
    }
  }
}
