//
//  ClientEmitterTests.swift
//

import InlineSnapshotTesting
import Testing

@testable import OpenAPICodegenCore

@Suite
struct ClientEmitterTests {

  @Test
  func emitsJSONRoundTripOperation() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "getBucket",
          method: .get,
          path: "/bucket/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: nil,
          responses: [
            IRResponse(statusCode: 200, isError: false, body: .json(.schemaRef("bucketSchema"))),
            IRResponse(statusCode: 404, isError: true, body: .json(.schemaRef("errorSchema"))),
          ]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      public struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        public init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        public func getBucket(bucketId: String) async throws -> BucketSchema {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/bucket/\(PathEncoding.segment(bucketId))")
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [404: ErrorSchema.self])
          return try JSONCoding.decoder.decode(BucketSchema.self, from: response.body)
        }
      }
      """#
    }
  }

  @Test
  func emitsMultipartUploadOperation() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "createObject",
          method: .post,
          path: "/object/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: .multipart(fields: [
            IRMultipartField(name: "file", type: .string, isFile: true),
            IRMultipartField(name: "cacheControl", type: .string, isFile: false),
          ]),
          responses: [
            IRResponse(statusCode: 200, isError: false, body: .none)
          ]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      public struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        public init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        public func createObject(bucketId: String, file: URL, cacheControl: String) async throws {
          var builder = HTTPRequestBuilder(method: .post, baseURL: baseURL, path: "/object/\(PathEncoding.segment(bucketId))")
          var formData = MultipartFormData()
          formData.append(MultipartFormData.Part(name: "file", filename: file.lastPathComponent, contentType: "application/octet-stream", source: .file(file)))
          formData.append(MultipartFormData.Part(name: "cacheControl", source: .data(Data(String(describing: cacheControl).utf8))))
          builder.setHeader("Content-Type", formData.contentType)
          builder.setBody(.multipart(formData))
          let response = try await transport.send(try builder.build())
          try response.checkStatus(errorTypes: [])
        }
      }
      """#
    }
  }

  @Test
  func emitsBinaryDownloadOperation() {
    let document = IRDocument(
      schemas: [],
      operations: [
        IROperation(
          operationId: "download",
          method: .get,
          path: "/object/{bucketId}",
          parameters: [
            IRParameter(name: "bucketId", location: .path, type: .string, isOptional: false)
          ],
          requestBody: nil,
          responses: [IRResponse(statusCode: 200, isError: false, body: .binary)]
        )
      ]
    )

    let output = SwiftEmitter.emitClient(document, clientName: "StorageOpenAPIClient")

    assertInlineSnapshot(of: output, as: .lines) {
      #"""
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      public struct StorageOpenAPIClient: Sendable {
        private let baseURL: URL
        private let transport: any HTTPTransport

        public init(baseURL: URL, transport: any HTTPTransport = URLSessionTransport()) {
          self.baseURL = baseURL
          self.transport = transport
        }

        public func download(bucketId: String) async throws -> AsyncThrowingStream<Data, any Error> {
          var builder = HTTPRequestBuilder(method: .get, baseURL: baseURL, path: "/object/\(PathEncoding.segment(bucketId))")
          let stream = try await transport.stream(try builder.build())
          guard stream.head.isSuccess else {
            throw HTTPError.unexpectedStatus(status: stream.head.status, body: Data())
          }
          return stream.body
        }
      }
      """#
    }
  }
}
