//
//  ModelEmitterTests.swift
//

import InlineSnapshotTesting
import Testing

@testable import OpenAPICodegenCore

@Suite
struct ModelEmitterTests {

  @Test
  func emitsStructWithCodingKeys() {
    let document = IRDocument(
      schemas: [
        IRSchema(
          name: "bucketSchema",
          kind: .object(properties: [
            IRProperty(name: "id", type: .string, isOptional: false),
            IRProperty(name: "file_size_limit", type: .integer, isOptional: true),
          ])
        )
      ],
      operations: []
    )

    let output = SwiftEmitter.emitModels(document)

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct BucketSchema: Codable, Sendable, Hashable {
        internal var id: String
        internal var fileSizeLimit: Int?

        enum CodingKeys: String, CodingKey {
          case id = "id"
          case fileSizeLimit = "file_size_limit"
        }
      }

      """
    }
  }

  @Test
  func emitsStringEnum() {
    let document = IRDocument(
      schemas: [IRSchema(name: "visibility", kind: .stringEnum(cases: ["public", "private"]))],
      operations: []
    )

    let output = SwiftEmitter.emitModels(document)

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal enum Visibility: String, Codable, Sendable, Hashable {
        case `public` = "public"
        case `private` = "private"
      }

      """
    }
  }

  @Test
  func marksSchemasReferencedByErrorResponsesAsAPIError() {
    let document = IRDocument(
      schemas: [
        IRSchema(
          name: "errorSchema",
          kind: .object(properties: [IRProperty(name: "message", type: .string, isOptional: false)])
        )
      ],
      operations: [
        IROperation(
          operationId: "getBucket",
          method: .get,
          path: "/bucket/{id}",
          parameters: [],
          requestBody: nil,
          responses: [
            IRResponse(statusCode: 404, isError: true, body: .json(.schemaRef("errorSchema")))
          ]
        )
      ]
    )

    let output = SwiftEmitter.emitModels(document)

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal struct ErrorSchema: Codable, Sendable, Hashable, APIError {
        internal var message: String

        enum CodingKeys: String, CodingKey {
          case message = "message"
        }
      }

      """
    }
  }

  @Test
  func emitsUnionAsTaggedEnum() {
    let document = IRDocument(
      schemas: [
        IRSchema(
          name: "bucketCreate_fileSizeLimit",
          kind: .union(cases: [
            IRUnionCase(name: "integer", type: .integer),
            IRUnionCase(name: "string", type: .string),
          ])
        )
      ],
      operations: []
    )

    let output = SwiftEmitter.emitModels(document)

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      import HTTPRuntime

      internal enum BucketCreateFileSizeLimit: Codable, Sendable, Hashable {
        case integer(Int)
        case string(String)

        internal init(from decoder: any Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let value = try? container.decode(Int.self) {
            self = .integer(value)
            return
          }
          if let value = try? container.decode(String.self) {
            self = .string(value)
            return
          }
          throw DecodingError.typeMismatch(
            BucketCreateFileSizeLimit.self,
            DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "no matching case")
          )
        }

        internal func encode(to encoder: any Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .integer(let value): try container.encode(value)
          case .string(let value): try container.encode(value)
          }
        }
      }

      """
    }
  }

  @Test
  func emitsPublicAccessLevelWhenRequested() {
    let document = IRDocument(
      schemas: [
        IRSchema(
          name: "bucketSchema",
          kind: .object(properties: [
            IRProperty(name: "id", type: .string, isOptional: false)
          ])
        )
      ],
      operations: []
    )

    let output = SwiftEmitter.emitModels(document, accessLevel: .public)

    assertInlineSnapshot(of: output, as: .lines) {
      """
      // Code generated by openapi-codegen. DO NOT EDIT.

      import Foundation
      public import HTTPRuntime

      public struct BucketSchema: Codable, Sendable, Hashable {
        public var id: String

        enum CodingKeys: String, CodingKey {
          case id = "id"
        }
      }

      """
    }
  }
}
